# Generated by RLS soh_ap transpiler
from .enums.gen.py import *
from .rls_match import rls_match

def _can_get_drop_gold_skulltula(bundle, distance: EnemyDistance) -> bool:
    return rls_match((lambda distance=distance: distance == EnemyDistance.ED_CLOSE or distance == EnemyDistance.ED_SHORT_JUMPSLASH or distance == EnemyDistance.ED_MASTER_SWORD_JUMPSLASH or distance == EnemyDistance.ED_LONG_JUMPSLASH or distance == EnemyDistance.ED_BOMB_THROW or distance == EnemyDistance.ED_BOOMERANG), (lambda: can_use(bundle, RandomizerGet.RG_BOOMERANG)), True, (lambda distance=distance: distance == EnemyDistance.ED_HOOKSHOT), (lambda: can_use(bundle, RandomizerGet.RG_HOOKSHOT)), True, (lambda distance=distance: distance == EnemyDistance.ED_LONGSHOT), (lambda: can_use(bundle, RandomizerGet.RG_LONGSHOT)), False)

def _can_kill_gold_skulltula(bundle, distance: EnemyDistance, wall_or_floor: bool) -> bool:
    return rls_match((lambda distance=distance: distance == EnemyDistance.ED_CLOSE), (lambda: can_use(bundle, RandomizerGet.RG_MEGATON_HAMMER)), True, (lambda distance=distance: distance == EnemyDistance.ED_SHORT_JUMPSLASH), (lambda: can_use(bundle, RandomizerGet.RG_KOKIRI_SWORD)), True, (lambda distance=distance: distance == EnemyDistance.ED_MASTER_SWORD_JUMPSLASH), (lambda: can_use(bundle, RandomizerGet.RG_MASTER_SWORD)), True, (lambda distance=distance: distance == EnemyDistance.ED_LONG_JUMPSLASH), (lambda: can_use(bundle, RandomizerGet.RG_BIGGORON_SWORD) or can_use(bundle, RandomizerGet.RG_STICKS)), True, (lambda distance=distance: distance == EnemyDistance.ED_BOMB_THROW), (lambda: can_use(bundle, RandomizerGet.RG_BOMB_BAG)), True, (lambda distance=distance: distance == EnemyDistance.ED_BOOMERANG), (lambda: can_use(bundle, RandomizerGet.RG_BOOMERANG) or can_use(bundle, RandomizerGet.RG_DINS_FIRE)), True, (lambda distance=distance: distance == EnemyDistance.ED_HOOKSHOT), (lambda: can_use(bundle, RandomizerGet.RG_HOOKSHOT)), True, (lambda distance=distance: distance == EnemyDistance.ED_LONGSHOT), (lambda: can_use(bundle, RandomizerGet.RG_LONGSHOT) or wall_or_floor and can_use(bundle, RandomizerGet.RG_BOMBCHU_5)), True, (lambda distance=distance: distance == EnemyDistance.ED_FAR), (lambda: can_use(bundle, RandomizerGet.RG_FAIRY_SLINGSHOT) or can_use(bundle, RandomizerGet.RG_FAIRY_BOW)), False)

def call_gossip_fairy(bundle) -> bool:
    return call_gossip_fairy_except_suns(bundle) or can_use(bundle, RandomizerGet.RG_SUNS_SONG)

def call_gossip_fairy_except_suns(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_ZELDAS_LULLABY) or can_use(bundle, RandomizerGet.RG_EPONAS_SONG) or can_use(bundle, RandomizerGet.RG_SONG_OF_TIME)

def can_avoid(bundle, e: RandomizerEnemy, grounded: bool = False, quantity: int = 1) -> bool:
    return can_kill(bundle, e, EnemyDistance.ED_CLOSE, True, quantity, False, False) or rls_match((lambda e=e: e == RandomizerEnemy.RE_GOLD_SKULLTULA), (lambda: True), False)

def can_break_lower_beehives(bundle) -> bool:
    return can_break_upper_beehives(bundle) or can_use(bundle, RandomizerGet.RG_BOMB_BAG)

def can_break_upper_beehives(bundle) -> bool:
    return hookshot_or_boomerang(bundle) or trick(bundle, RandomizerTrick.RT_BOMBCHU_BEEHIVES) and can_use(bundle, RandomizerGet.RG_BOMBCHU_5) or bundle[2].options.RSK_SLINGBOW_BREAK_BEEHIVES and (can_use(bundle, RandomizerGet.RG_FAIRY_BOW) or can_use(bundle, RandomizerGet.RG_FAIRY_SLINGSHOT))

def can_climb_ladder(bundle) -> bool:
    return has(bundle, RandomizerGet.RG_CLIMB) or trick(bundle, RandomizerTrick.RT_HOOKSHOT_LADDERS) and can_use(bundle, RandomizerGet.RG_HOOKSHOT)

def can_cut_shrubs(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_KOKIRI_SWORD) or can_use(bundle, RandomizerGet.RG_BOOMERANG) or has_explosives(bundle) or has(bundle, RandomizerGet.RG_GORONS_BRACELET) or can_use(bundle, RandomizerGet.RG_MASTER_SWORD) or can_use(bundle, RandomizerGet.RG_MEGATON_HAMMER) or can_use(bundle, RandomizerGet.RG_BIGGORON_SWORD) or can_use(bundle, RandomizerGet.RG_GIANTS_KNIFE)

def can_get_deku_baba_nuts(bundle) -> bool:
    return can_jumpslash(bundle) or can_use(bundle, RandomizerGet.RG_FAIRY_SLINGSHOT) or can_use(bundle, RandomizerGet.RG_FAIRY_BOW) or has_explosives(bundle) or can_use(bundle, RandomizerGet.RG_DINS_FIRE)

def can_get_deku_baba_sticks(bundle) -> bool:
    return can_use_sword(bundle) or can_use(bundle, RandomizerGet.RG_BOOMERANG)

def can_get_drop(bundle, e: RandomizerEnemy, distance: EnemyDistance = EnemyDistance.ED_CLOSE, above_link: bool = False) -> bool:
    return can_kill(bundle, e, distance, True, 1, False, False) and (distance_to_int(bundle, distance) <= distance_to_int(bundle, EnemyDistance.ED_MASTER_SWORD_JUMPSLASH) or rls_match((lambda e=e: e == RandomizerEnemy.RE_GOLD_SKULLTULA), (lambda: _can_get_drop_gold_skulltula(bundle, distance)), False, (lambda e=e: e == RandomizerEnemy.RE_KEESE or e == RandomizerEnemy.RE_FIRE_KEESE or e == RandomizerEnemy.RE_GUAY), (lambda: True), False, (lambda: true), (lambda: above_link or distance_to_int(bundle, distance) <= distance_to_int(bundle, EnemyDistance.ED_BOOMERANG) and can_use(bundle, RandomizerGet.RG_BOOMERANG)), False))

def can_get_night_time_gs(bundle) -> bool:
    return at_night(bundle) and (can_use(bundle, RandomizerGet.RG_SUNS_SONG) or not bundle[2].options.RSK_SKULLS_SUNS_SONG)

def can_jumpslash(bundle) -> bool:
    return can_jumpslash_except_hammer(bundle) or can_use(bundle, RandomizerGet.RG_MEGATON_HAMMER)

def can_jumpslash_except_hammer(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_STICKS) or can_use_sword(bundle)

def can_kill(bundle, e: RandomizerEnemy, distance: EnemyDistance = EnemyDistance.ED_CLOSE, wall_or_floor: bool = True, quantity: int = 1, timer: bool = False, in_water: bool = False) -> bool:
    return rls_match((lambda e=e: e == RandomizerEnemy.RE_GOLD_SKULLTULA), (lambda: _can_kill_gold_skulltula(bundle, distance, wall_or_floor)), False)

def can_open_storms_grotto(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS) and (has(bundle, RandomizerGet.RG_STONE_OF_AGONY) or trick(bundle, RandomizerTrick.RT_GROTTOS_WITHOUT_AGONY))

def can_pass(bundle, e: RandomizerEnemy, distance: EnemyDistance = EnemyDistance.ED_CLOSE, wall_or_floor: bool = True) -> bool:
    return can_kill(bundle, e, distance, wall_or_floor, 1, False, False) or rls_match((lambda e=e: e == RandomizerEnemy.RE_GOLD_SKULLTULA), (lambda: True), False)

def can_spawn_soil_skull(bundle, bean: RandomizerGet) -> bool:
    return is_child(bundle) and can_use(bundle, RandomizerGet.RG_BOTTLE_WITH_BUGS) and has(bundle, bean)

def can_use_sword(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_KOKIRI_SWORD) or can_use(bundle, RandomizerGet.RG_MASTER_SWORD) or can_use(bundle, RandomizerGet.RG_BIGGORON_SWORD)

def distance_to_int(bundle, distance: EnemyDistance) -> int:
    return rls_match((lambda distance=distance: distance == EnemyDistance.ED_CLOSE), (lambda: 0), False, (lambda distance=distance: distance == EnemyDistance.ED_SHORT_JUMPSLASH), (lambda: 1), False, (lambda distance=distance: distance == EnemyDistance.ED_MASTER_SWORD_JUMPSLASH), (lambda: 2), False, (lambda distance=distance: distance == EnemyDistance.ED_LONG_JUMPSLASH), (lambda: 3), False, (lambda distance=distance: distance == EnemyDistance.ED_BOMB_THROW), (lambda: 4), False, (lambda distance=distance: distance == EnemyDistance.ED_BOOMERANG), (lambda: 5), False, (lambda distance=distance: distance == EnemyDistance.ED_HOOKSHOT), (lambda: 6), False, (lambda distance=distance: distance == EnemyDistance.ED_LONGSHOT), (lambda: 7), False, (lambda distance=distance: distance == EnemyDistance.ED_FAR), (lambda: 8), False)

def has_bottle(bundle) -> bool:
    return bottle_count(bundle) >= 1

def has_explosives(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_BOMB_BAG) or can_use(bundle, RandomizerGet.RG_BOMBCHU_5)

def hookshot_or_boomerang(bundle) -> bool:
    return can_use(bundle, RandomizerGet.RG_HOOKSHOT) or can_use(bundle, RandomizerGet.RG_BOOMERANG)

def wallet_capacity(bundle) -> int:
    return 999 if has(bundle, RandomizerGet.RG_TYCOON_WALLET) else 500 if has(bundle, RandomizerGet.RG_GIANT_WALLET) else 200 if has(bundle, RandomizerGet.RG_ADULT_WALLET) else 99 if has(bundle, RandomizerGet.RG_CHILD_WALLET) else 0
