# Generated by RLS soh_ap transpiler
from .functions.gen.py import *

if TYPE_CHECKING:
    from ... import SohWorld

def set_region_rules(world: "SohWorld") -> None:
    # Adult Spawn
    # Events
    add_events(RandomizerRegion.RR_ADULT_SPAWN, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_ADULT_SPAWN, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_ADULT_SPAWN, world, [
        (RandomizerRegion.RR_TEMPLE_OF_TIME, lambda bundle: True),
    ])

    # Bolero of Fire Warp
    # Events
    add_events(RandomizerRegion.RR_BOLERO_OF_FIRE_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_BOLERO_OF_FIRE_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_BOLERO_OF_FIRE_WARP, world, [
        (RandomizerRegion.RR_DMC_PAD_ENTRY, lambda bundle: True),
    ])

    # Child Spawn
    # Events
    add_events(RandomizerRegion.RR_CHILD_SPAWN, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_CHILD_SPAWN, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_CHILD_SPAWN, world, [
        (RandomizerRegion.RR_KF_LINKS_HOUSE, lambda bundle: True),
    ])

    # KF Boulder Loop
    # Events
    add_events(RandomizerRegion.RR_KF_BOULDER_LOOP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_BOULDER_LOOP, world, [
        (RandomizerCheck.RC_KF_KOKIRI_SWORD_CHEST, lambda bundle: is_child(bundle) and has(bundle, RandomizerGet.RG_OPEN_CHEST)),
        (RandomizerCheck.RC_KF_BOULDER_RUPEE_1, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_BOULDER_RUPEE_2, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_MAZE_1, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_MAZE_2, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_MAZE_3, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_BOULDER_LOOP, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: can_use(bundle, RandomizerGet.RG_CRAWL)),
    ])

    # KF House of Twins
    # Events
    add_events(RandomizerRegion.RR_KF_HOUSE_OF_TWINS, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_HOUSE_OF_TWINS, world, [
        (RandomizerCheck.RC_KF_TWINS_HOUSE_POT_1, lambda bundle: has(bundle, RandomizerGet.RG_POWER_BRACELET)),
        (RandomizerCheck.RC_KF_TWINS_HOUSE_POT_2, lambda bundle: has(bundle, RandomizerGet.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_HOUSE_OF_TWINS, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Know It All House
    # Events
    add_events(RandomizerRegion.RR_KF_KNOW_IT_ALL_HOUSE, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_KNOW_IT_ALL_HOUSE, world, [
        (RandomizerCheck.RC_KF_BROTHERS_HOUSE_POT_1, lambda bundle: has(bundle, RandomizerGet.RG_POWER_BRACELET)),
        (RandomizerCheck.RC_KF_BROTHERS_HOUSE_POT_2, lambda bundle: has(bundle, RandomizerGet.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_KNOW_IT_ALL_HOUSE, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Kokiri Shop
    # Events
    add_events(RandomizerRegion.RR_KF_KOKIRI_SHOP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_KOKIRI_SHOP, world, [
        (RandomizerCheck.RC_KF_SHOP_ITEM_1, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_2, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_3, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_4, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_5, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_6, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_7, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
        (RandomizerCheck.RC_KF_SHOP_ITEM_8, lambda bundle: has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and check_price(bundle, RandomizerCheck.RC_UNKNOWN_CHECK) <= wallet_capacity(bundle)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_KOKIRI_SHOP, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Link's House
    # Events
    add_events(RandomizerRegion.RR_KF_LINKS_HOUSE, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_LINKS_HOUSE, world, [
        (RandomizerCheck.RC_KF_LINKS_HOUSE_COW, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_EPONAS_SONG) and flag(bundle, LOGIC_LINKS_COW)),
        (RandomizerCheck.RC_KF_LINKS_HOUSE_POT, lambda bundle: has(bundle, RandomizerGet.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_LINKS_HOUSE, world, [
        (RandomizerRegion.RR_KF_LINKS_PORCH, lambda bundle: True),
    ])

    # KF Link's Porch
    # Events
    add_events(RandomizerRegion.RR_KF_LINKS_PORCH, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_LINKS_PORCH, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_LINKS_PORCH, world, [
        (RandomizerRegion.RR_KF_LINKS_HOUSE, lambda bundle: True),
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Mido's House
    # Events
    add_events(RandomizerRegion.RR_KF_MIDOS_HOUSE, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_MIDOS_HOUSE, world, [
        (RandomizerCheck.RC_KF_MIDOS_TOP_LEFT_CHEST, lambda bundle: has(bundle, RandomizerGet.RG_OPEN_CHEST)),
        (RandomizerCheck.RC_KF_MIDOS_TOP_RIGHT_CHEST, lambda bundle: has(bundle, RandomizerGet.RG_OPEN_CHEST)),
        (RandomizerCheck.RC_KF_MIDOS_BOTTOM_LEFT_CHEST, lambda bundle: has(bundle, RandomizerGet.RG_OPEN_CHEST)),
        (RandomizerCheck.RC_KF_MIDOS_BOTTOM_RIGHT_CHEST, lambda bundle: has(bundle, RandomizerGet.RG_OPEN_CHEST)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_MIDOS_HOUSE, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Outside Deku Tree
    # Events
    add_events(RandomizerRegion.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_STICK_ACCESS, Events.LOGIC_STICK_ACCESS, lambda bundle: can_get_deku_baba_sticks(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_NUT_ACCESS, Events.LOGIC_NUT_ACCESS, lambda bundle: can_get_deku_baba_nuts(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, lambda bundle: is_child(bundle) and has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and can_use(bundle, RandomizerGet.RG_KOKIRI_SWORD) and can_use(bundle, RandomizerGet.RG_DEKU_SHIELD)),
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (RandomizerCheck.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (RandomizerCheck.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (RandomizerCheck.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE, lambda bundle: True),
        (RandomizerCheck.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE, lambda bundle: True),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (RandomizerRegion.RR_DEKU_TREE_ENTRYWAY, lambda bundle: is_child(bundle) or bundle[2].options.RSK_SHUFFLE_DUNGEON_ENTRANCES != RO_DUNGEON_ENTRANCE_SHUFFLE_OFF and (bundle[2].options.RSK_FOREST == RO_CLOSED_FOREST_OFF or flag(bundle, LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD))),
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: is_adult(bundle) and (can_pass(bundle, RandomizerEnemy.RE_BIG_SKULLTULA, EnemyDistance.ED_CLOSE, True) or flag(bundle, LOGIC_DEKU_TREE_CLEAR)) or bundle[2].options.RSK_FOREST == RO_CLOSED_FOREST_OFF or flag(bundle, LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD)),
    ])

    # KF Outside Lost Woods
    # Events
    add_events(RandomizerRegion.RR_KF_OUTSIDE_LOST_WOODS, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_OUTSIDE_LOST_WOODS, world, [
        (RandomizerCheck.RC_KF_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (RandomizerCheck.RC_KF_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_BOOMERANG)),
        (RandomizerCheck.RC_KF_GOSSIP_STONE, lambda bundle: True),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_OUTSIDE_LOST_WOODS, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
        (RandomizerRegion.RR_THE_LOST_WOODS, lambda bundle: True),
        (RandomizerRegion.RR_KF_RUPEE_ALCOVE, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS))),
        (RandomizerRegion.RR_KF_STORMS_GROTTO, lambda bundle: can_open_storms_grotto(bundle)),
    ])

    # KF Alcove
    # Events
    add_events(RandomizerRegion.RR_KF_RUPEE_ALCOVE, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_RUPEE_ALCOVE, world, [
        (RandomizerCheck.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerCheck.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_RUPEE_ALCOVE, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Saria's House
    # Events
    add_events(RandomizerRegion.RR_KF_SARIAS_HOUSE, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_SARIAS_HOUSE, world, [
        (RandomizerCheck.RC_KF_SARIAS_TOP_LEFT_HEART, lambda bundle: True),
        (RandomizerCheck.RC_KF_SARIAS_TOP_RIGHT_HEART, lambda bundle: True),
        (RandomizerCheck.RC_KF_SARIAS_BOTTOM_LEFT_HEART, lambda bundle: True),
        (RandomizerCheck.RC_KF_SARIAS_BOTTOM_RIGHT_HEART, lambda bundle: True),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_SARIAS_HOUSE, world, [
        (RandomizerRegion.RR_KOKIRI_FOREST, lambda bundle: True),
    ])

    # KF Storms Grotto
    # Events
    add_events(RandomizerRegion.RR_KF_STORMS_GROTTO, world, [
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy(bundle) or can_use(bundle, RandomizerGet.RG_STICKS)),
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_BUG_ACCESS, Events.LOGIC_BUG_ACCESS, lambda bundle: can_cut_shrubs(bundle)),
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_FISH_ACCESS, Events.LOGIC_FISH_ACCESS, lambda bundle: True),
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KF_STORMS_GROTTO, world, [
        (RandomizerCheck.RC_KF_STORMS_GROTTO_CHEST, lambda bundle: has(bundle, RandomizerGet.RG_OPEN_CHEST)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_BEEHIVE_LEFT, lambda bundle: can_break_lower_beehives(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_BEEHIVE_RIGHT, lambda bundle: can_break_lower_beehives(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_FISH, lambda bundle: has_bottle(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GRASS_1, lambda bundle: can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GRASS_2, lambda bundle: can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GRASS_3, lambda bundle: can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GRASS_4, lambda bundle: can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_STORMS_GROTTO_GOSSIP_STONE, lambda bundle: True),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KF_STORMS_GROTTO, world, [
        (RandomizerRegion.RR_KF_OUTSIDE_LOST_WOODS, lambda bundle: True),
    ])

    # Kokiri Forest
    # Events
    add_events(RandomizerRegion.RR_KOKIRI_FOREST, world, [
        (EventLocations.RR_KOKIRI_FOREST_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy_except_suns(bundle) or is_child(bundle) and can_use(bundle, RandomizerGet.RG_MAGIC_BEAN) and has(bundle, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) and can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (EventLocations.RR_KOKIRI_FOREST_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, lambda bundle: is_child(bundle) and has(bundle, RandomizerGet.RG_SPEAK_KOKIRI) and can_use(bundle, RandomizerGet.RG_KOKIRI_SWORD) and can_use(bundle, RandomizerGet.RG_DEKU_SHIELD)),
    ])
    # Locations
    add_locations(RandomizerRegion.RR_KOKIRI_FOREST, world, [
        (RandomizerCheck.RC_KF_BEAN_SPROUT_FAIRY_1, lambda bundle: is_child(bundle) and can_use(bundle, RandomizerGet.RG_MAGIC_BEAN) and has(bundle, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) and can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_BEAN_SPROUT_FAIRY_2, lambda bundle: is_child(bundle) and can_use(bundle, RandomizerGet.RG_MAGIC_BEAN) and has(bundle, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) and can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_BEAN_SPROUT_FAIRY_3, lambda bundle: is_child(bundle) and can_use(bundle, RandomizerGet.RG_MAGIC_BEAN) and has(bundle, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) and can_use(bundle, RandomizerGet.RG_SONG_OF_STORMS)),
        (RandomizerCheck.RC_KF_BRIDGE_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_BEHIND_MIDOS_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_SOUTH_GRASS_WEST_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_SOUTH_GRASS_EAST_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_NORTH_GRASS_WEST_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_NORTH_GRASS_EAST_RUPEE, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_SARIAS_ROOF_WEST_HEART, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_SARIAS_ROOF_EAST_HEART, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_SARIAS_ROOF_NORTH_HEART, lambda bundle: is_child(bundle)),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) or can_use(bundle, RandomizerGet.RG_BOOMERANG))),
        (RandomizerCheck.RC_KF_GS_KNOW_IT_ALL_HOUSE, lambda bundle: is_child(bundle) and can_kill(bundle, RandomizerEnemy.RE_GOLD_SKULLTULA, EnemyDistance.ED_CLOSE, True, 1, False, False) and can_get_night_time_gs(bundle)),
        (RandomizerCheck.RC_KF_GS_BEAN_PATCH, lambda bundle: can_spawn_soil_skull(bundle, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) and can_kill(bundle, RandomizerEnemy.RE_GOLD_SKULLTULA, EnemyDistance.ED_CLOSE, True, 1, False, False)),
        (RandomizerCheck.RC_KF_GS_HOUSE_OF_TWINS, lambda bundle: is_adult(bundle) and can_get_night_time_gs(bundle) and (can_get_drop(bundle, RandomizerEnemy.RE_GOLD_SKULLTULA, EnemyDistance.ED_BOOMERANG, False) or trick(bundle, RandomizerTrick.RT_KF_ADULT_GS) and can_use(bundle, RandomizerGet.RG_HOVER_BOOTS) and can_kill(bundle, RandomizerEnemy.RE_GOLD_SKULLTULA, EnemyDistance.ED_SHORT_JUMPSLASH, True, 1, False, False))),
        (RandomizerCheck.RC_KF_CHILD_GRASS_1, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_2, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_3, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_4, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_5, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_6, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_7, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_8, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_9, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_10, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_11, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_CHILD_GRASS_12, lambda bundle: is_child(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_1, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_2, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_3, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_4, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_5, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_6, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_7, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_8, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_9, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_10, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_11, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_12, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_13, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_14, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_15, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_16, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_17, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_18, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_19, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
        (RandomizerCheck.RC_KF_ADULT_GRASS_20, lambda bundle: is_adult(bundle) and can_cut_shrubs(bundle)),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_KOKIRI_FOREST, world, [
        (RandomizerRegion.RR_KF_BOULDER_LOOP, lambda bundle: can_use(bundle, RandomizerGet.RG_CRAWL)),
        (RandomizerRegion.RR_KF_LINKS_PORCH, lambda bundle: can_climb_ladder(bundle) if is_child(bundle) else has(bundle, RandomizerGet.RG_CLIMB) or can_use(bundle, RandomizerGet.RG_HOVER_BOOTS)),
        (RandomizerRegion.RR_KF_MIDOS_HOUSE, lambda bundle: True),
        (RandomizerRegion.RR_KF_SARIAS_HOUSE, lambda bundle: True),
        (RandomizerRegion.RR_KF_HOUSE_OF_TWINS, lambda bundle: True),
        (RandomizerRegion.RR_KF_KNOW_IT_ALL_HOUSE, lambda bundle: True),
        (RandomizerRegion.RR_KF_KOKIRI_SHOP, lambda bundle: True),
        (RandomizerRegion.RR_KF_OUTSIDE_DEKU_TREE, lambda bundle: flag(bundle, LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD) or bundle[2].options.RSK_FOREST == RO_CLOSED_FOREST_OFF or is_adult(bundle) and (can_pass(bundle, RandomizerEnemy.RE_BIG_SKULLTULA, EnemyDistance.ED_CLOSE, True) or flag(bundle, LOGIC_FOREST_TEMPLE_CLEAR))),
        (RandomizerRegion.RR_KF_OUTSIDE_LOST_WOODS, lambda bundle: has(bundle, RandomizerGet.RG_CLIMB) or can_use(bundle, RandomizerGet.RG_HOOKSHOT) or is_adult(bundle) and (can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL) or trick(bundle, RandomizerTrick.RT_UNINTUITIVE_JUMPS))),
        (RandomizerRegion.RR_KF_RUPEE_ALCOVE, lambda bundle: is_adult(bundle) and can_plant_bean(bundle, RandomizerRegion.RR_KOKIRI_FOREST, RandomizerGet.RG_KOKIRI_FOREST_BEAN_SOUL)),
        (RandomizerRegion.RR_LW_BRIDGE_FROM_FOREST, lambda bundle: is_adult(bundle) or bundle[2].options.RSK_FOREST != RO_CLOSED_FOREST_ON or flag(bundle, LOGIC_DEKU_TREE_CLEAR)),
    ])

    # Minuet of Forest Warp
    # Events
    add_events(RandomizerRegion.RR_MINUET_OF_FOREST_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_MINUET_OF_FOREST_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_MINUET_OF_FOREST_WARP, world, [
        (RandomizerRegion.RR_SACRED_FOREST_MEADOW, lambda bundle: True),
    ])

    # Nocturne of Shadow Warp
    # Events
    add_events(RandomizerRegion.RR_NOCTURNE_OF_SHADOW_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_NOCTURNE_OF_SHADOW_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_NOCTURNE_OF_SHADOW_WARP, world, [
        (RandomizerRegion.RR_GRAVEYARD_WARP_PAD_REGION, lambda bundle: True),
    ])

    # Prelude of Light Warp
    # Events
    add_events(RandomizerRegion.RR_PRELUDE_OF_LIGHT_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_PRELUDE_OF_LIGHT_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_PRELUDE_OF_LIGHT_WARP, world, [
        (RandomizerRegion.RR_TEMPLE_OF_TIME, lambda bundle: True),
    ])

    # Requiem of Spirit Warp
    # Events
    add_events(RandomizerRegion.RR_REQUIEM_OF_SPIRIT_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_REQUIEM_OF_SPIRIT_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_REQUIEM_OF_SPIRIT_WARP, world, [
        (RandomizerRegion.RR_DESERT_COLOSSUS, lambda bundle: True),
    ])

    # Root
    # Events
    add_events(RandomizerRegion.RR_ROOT, world, [
        (EventLocations.RR_ROOT_LOGIC_KAKARIKO_GATE_OPEN, Events.LOGIC_KAKARIKO_GATE_OPEN, lambda bundle: bundle[2].options.RSK_KAK_GATE == RO_KAK_GATE_OPEN),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER, Events.LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER, lambda bundle: bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FREE),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER, Events.LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER, lambda bundle: bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FREE or bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FAST),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER, Events.LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER, lambda bundle: bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FREE or bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FAST),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_SLOPE_CARPENTER, Events.LOGIC_TH_COULD_FREE_SLOPE_CARPENTER, lambda bundle: bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FREE or bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FAST),
        (EventLocations.RR_ROOT_LOGIC_TH_RESCUED_ALL_CARPENTERS, Events.LOGIC_TH_RESCUED_ALL_CARPENTERS, lambda bundle: bundle[2].options.RSK_GERUDO_FORTRESS == RO_GF_CARPENTERS_FREE),
        (EventLocations.RR_ROOT_LOGIC_FREED_EPONA, Events.LOGIC_FREED_EPONA, lambda bundle: bundle[2].options.RSK_SKIP_EPONA_RACE == RO_GENERIC_YES),
    ])
    # Locations
    add_locations(RandomizerRegion.RR_ROOT, world, [
        (RandomizerCheck.RC_LINKS_POCKET, lambda bundle: True),
        (RandomizerCheck.RC_TRIFORCE_COMPLETED, lambda bundle: collected_triforce_pieces(bundle) >= required_triforce_pieces(bundle)),
        (RandomizerCheck.RC_SARIA_SONG_HINT, lambda bundle: can_use(bundle, RandomizerGet.RG_SARIAS_SONG)),
        (RandomizerCheck.RC_SONG_FROM_IMPA, lambda bundle: bundle[2].options.RSK_SKIP_CHILD_ZELDA == RO_GENERIC_YES),
        (RandomizerCheck.RC_HC_MALON_EGG, lambda bundle: bundle[2].options.RSK_SKIP_CHILD_ZELDA == RO_GENERIC_YES),
        (RandomizerCheck.RC_HC_ZELDAS_LETTER, lambda bundle: bundle[2].options.RSK_SKIP_CHILD_ZELDA == RO_GENERIC_YES),
        (RandomizerCheck.RC_TOT_MASTER_SWORD, lambda bundle: bundle[2].options.RSK_SELECTED_STARTING_AGE == RO_AGE_ADULT),
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_ROOT, world, [
        (RandomizerRegion.RR_ROOT_EXITS, lambda bundle: True),
    ])

    # Root Exits
    # Events
    add_events(RandomizerRegion.RR_ROOT_EXITS, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_ROOT_EXITS, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_ROOT_EXITS, world, [
        (RandomizerRegion.RR_CHILD_SPAWN, lambda bundle: is_child(bundle)),
        (RandomizerRegion.RR_ADULT_SPAWN, lambda bundle: is_adult(bundle)),
        (RandomizerRegion.RR_MINUET_OF_FOREST_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_MINUET_OF_FOREST)),
        (RandomizerRegion.RR_BOLERO_OF_FIRE_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_BOLERO_OF_FIRE)),
        (RandomizerRegion.RR_SERENADE_OF_WATER_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_SERENADE_OF_WATER)),
        (RandomizerRegion.RR_NOCTURNE_OF_SHADOW_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_NOCTURNE_OF_SHADOW)),
        (RandomizerRegion.RR_REQUIEM_OF_SPIRIT_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_REQUIEM_OF_SPIRIT)),
        (RandomizerRegion.RR_PRELUDE_OF_LIGHT_WARP, lambda bundle: can_use(bundle, RandomizerGet.RG_PRELUDE_OF_LIGHT)),
    ])

    # Serenade of Water Warp
    # Events
    add_events(RandomizerRegion.RR_SERENADE_OF_WATER_WARP, world, [
    ])
    # Locations
    add_locations(RandomizerRegion.RR_SERENADE_OF_WATER_WARP, world, [
    ])
    # Exits
    connect_regions(RandomizerRegion.RR_SERENADE_OF_WATER_WARP, world, [
        (RandomizerRegion.RR_LAKE_HYLIA, lambda bundle: True),
    ])

