# Generated by RLS soh_ap transpiler
from .LogicHelpers import *

if TYPE_CHECKING:
    from ... import SohWorld

def set_region_rules(world: "SohWorld") -> None:
    # Adult Spawn
    # Exits
    connect_regions(Regions.RR_ADULT_SPAWN, world, [
        (Regions.RR_TEMPLE_OF_TIME, lambda bundle: True_()),
    ])

    # Bolero of Fire Warp
    # Exits
    connect_regions(Regions.RR_BOLERO_OF_FIRE_WARP, world, [
        (Regions.RR_DMC_PAD_ENTRY, lambda bundle: True_()),
    ])

    # Child Spawn
    # Exits
    connect_regions(Regions.RR_CHILD_SPAWN, world, [
        (Regions.RR_KF_LINKS_HOUSE, lambda bundle: True_()),
    ])

    # KF Boulder Loop
    # Locations
    add_locations(Regions.RR_KF_BOULDER_LOOP, world, [
        (Locations.RC_KF_KOKIRI_SWORD_CHEST, lambda bundle: is_child(bundle) & has_item(bundle, Items.RG_OPEN_CHEST)),
        (Locations.RC_KF_BOULDER_RUPEE_1, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_BOULDER_RUPEE_2, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_CHILD_GRASS_MAZE_1, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_MAZE_2, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_MAZE_3, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_BOULDER_LOOP, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: can_use(bundle, Items.RG_CRAWL)),
    ])

    # KF House of Twins
    # Locations
    add_locations(Regions.RR_KF_HOUSE_OF_TWINS, world, [
        (Locations.RC_KF_TWINS_HOUSE_POT_1, lambda bundle: has_item(bundle, Items.RG_POWER_BRACELET)),
        (Locations.RC_KF_TWINS_HOUSE_POT_2, lambda bundle: has_item(bundle, Items.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_HOUSE_OF_TWINS, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Know It All House
    # Locations
    add_locations(Regions.RR_KF_KNOW_IT_ALL_HOUSE, world, [
        (Locations.RC_KF_BROTHERS_HOUSE_POT_1, lambda bundle: has_item(bundle, Items.RG_POWER_BRACELET)),
        (Locations.RC_KF_BROTHERS_HOUSE_POT_2, lambda bundle: has_item(bundle, Items.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_KNOW_IT_ALL_HOUSE, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Kokiri Shop
    # Locations
    add_locations(Regions.RR_KF_KOKIRI_SHOP, world, [
        (Locations.RC_KF_SHOP_ITEM_1, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_1))),
        (Locations.RC_KF_SHOP_ITEM_2, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_2))),
        (Locations.RC_KF_SHOP_ITEM_3, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_3))),
        (Locations.RC_KF_SHOP_ITEM_4, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_4))),
        (Locations.RC_KF_SHOP_ITEM_5, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_5))),
        (Locations.RC_KF_SHOP_ITEM_6, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_6))),
        (Locations.RC_KF_SHOP_ITEM_7, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_7))),
        (Locations.RC_KF_SHOP_ITEM_8, lambda bundle: has_item(bundle, Items.RG_SPEAK_KOKIRI) & (can_afford_slot(Locations.RC_KF_SHOP_ITEM_8))),
    ])
    # Exits
    connect_regions(Regions.RR_KF_KOKIRI_SHOP, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Link's House
    # Locations
    add_locations(Regions.RR_KF_LINKS_HOUSE, world, [
        (Locations.RC_KF_LINKS_HOUSE_COW, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_EPONAS_SONG) & has_item(bundle, Events.LOGIC_LINKS_COW)),
        (Locations.RC_KF_LINKS_HOUSE_POT, lambda bundle: has_item(bundle, Items.RG_POWER_BRACELET)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_LINKS_HOUSE, world, [
        (Regions.RR_KF_LINKS_PORCH, lambda bundle: True_()),
    ])

    # KF Link's Porch
    # Exits
    connect_regions(Regions.RR_KF_LINKS_PORCH, world, [
        (Regions.RR_KF_LINKS_HOUSE, lambda bundle: True_()),
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Mido's House
    # Locations
    add_locations(Regions.RR_KF_MIDOS_HOUSE, world, [
        (Locations.RC_KF_MIDOS_TOP_LEFT_CHEST, lambda bundle: has_item(bundle, Items.RG_OPEN_CHEST)),
        (Locations.RC_KF_MIDOS_TOP_RIGHT_CHEST, lambda bundle: has_item(bundle, Items.RG_OPEN_CHEST)),
        (Locations.RC_KF_MIDOS_BOTTOM_LEFT_CHEST, lambda bundle: has_item(bundle, Items.RG_OPEN_CHEST)),
        (Locations.RC_KF_MIDOS_BOTTOM_RIGHT_CHEST, lambda bundle: has_item(bundle, Items.RG_OPEN_CHEST)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_MIDOS_HOUSE, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Outside Deku Tree
    # Events
    add_events(Regions.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_STICK_ACCESS, Events.LOGIC_STICK_ACCESS, lambda bundle: can_get_deku_baba_sticks(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_NUT_ACCESS, Events.LOGIC_NUT_ACCESS, lambda bundle: can_get_deku_baba_nuts(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (EventLocations.RR_KF_OUTSIDE_DEKU_TREE_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, lambda bundle: is_child(bundle) & has_item(bundle, Items.RG_SPEAK_KOKIRI) & can_use(bundle, Items.RG_KOKIRI_SWORD) & can_use(bundle, Items.RG_DEKU_SHIELD)),
    ])
    # Locations
    add_locations(Regions.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (Locations.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (Locations.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (Locations.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE, lambda bundle: True_()),
        (Locations.RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE, lambda bundle: True_()),
    ])
    # Exits
    connect_regions(Regions.RR_KF_OUTSIDE_DEKU_TREE, world, [
        (Regions.RR_DEKU_TREE_ENTRYWAY, lambda bundle: is_child(bundle) | (OptionFilter(RSK_SHUFFLE_DUNGEON_ENTRANCES, RandomizerSettingKey.RO_DUNGEON_ENTRANCE_SHUFFLE_OFF, "ne")) & ((OptionFilter(RSK_FOREST, RandomizerSettingKey.RO_CLOSED_FOREST_OFF)) | has_item(bundle, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD))),
        (Regions.RR_KOKIRI_FOREST, lambda bundle: is_adult(bundle) & (can_pass(bundle, Enemies.RE_BIG_SKULLTULA, EnemyDistance.ED_CLOSE, True) | has_item(bundle, Events.LOGIC_DEKU_TREE_CLEAR)) | (OptionFilter(RSK_FOREST, RandomizerSettingKey.RO_CLOSED_FOREST_OFF)) | has_item(bundle, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD)),
    ])

    # KF Outside Lost Woods
    # Locations
    add_locations(Regions.RR_KF_OUTSIDE_LOST_WOODS, world, [
        (Locations.RC_KF_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy_except_suns(bundle)),
        (Locations.RC_KF_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_BOOMERANG)),
        (Locations.RC_KF_GOSSIP_STONE, lambda bundle: True_()),
    ])
    # Exits
    connect_regions(Regions.RR_KF_OUTSIDE_LOST_WOODS, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
        (Regions.RR_THE_LOST_WOODS, lambda bundle: True_()),
        (Regions.RR_KF_RUPEE_ALCOVE, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS))),
        (Regions.RR_KF_STORMS_GROTTO, lambda bundle: can_open_storms_grotto(bundle)),
    ])

    # KF Alcove
    # Locations
    add_locations(Regions.RR_KF_RUPEE_ALCOVE, world, [
        (Locations.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Locations.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) & can_use(bundle, Items.RG_HOVER_BOOTS)),
    ])
    # Exits
    connect_regions(Regions.RR_KF_RUPEE_ALCOVE, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Saria's House
    # Locations
    add_locations(Regions.RR_KF_SARIAS_HOUSE, world, [
        (Locations.RC_KF_SARIAS_TOP_LEFT_HEART, lambda bundle: True_()),
        (Locations.RC_KF_SARIAS_TOP_RIGHT_HEART, lambda bundle: True_()),
        (Locations.RC_KF_SARIAS_BOTTOM_LEFT_HEART, lambda bundle: True_()),
        (Locations.RC_KF_SARIAS_BOTTOM_RIGHT_HEART, lambda bundle: True_()),
    ])
    # Exits
    connect_regions(Regions.RR_KF_SARIAS_HOUSE, world, [
        (Regions.RR_KOKIRI_FOREST, lambda bundle: True_()),
    ])

    # KF Storms Grotto
    # Events
    add_events(Regions.RR_KF_STORMS_GROTTO, world, [
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy(bundle) | can_use(bundle, Items.RG_STICKS)),
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_BUG_ACCESS, Events.LOGIC_BUG_ACCESS, lambda bundle: can_cut_shrubs(bundle)),
        (EventLocations.RR_KF_STORMS_GROTTO_LOGIC_FISH_ACCESS, Events.LOGIC_FISH_ACCESS, lambda bundle: True_()),
    ])
    # Locations
    add_locations(Regions.RR_KF_STORMS_GROTTO, world, [
        (Locations.RC_KF_STORMS_GROTTO_CHEST, lambda bundle: has_item(bundle, Items.RG_OPEN_CHEST)),
        (Locations.RC_KF_STORMS_GROTTO_BEEHIVE_LEFT, lambda bundle: can_break_lower_beehives(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_BEEHIVE_RIGHT, lambda bundle: can_break_lower_beehives(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY, lambda bundle: call_gossip_fairy(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY_BIG, lambda bundle: can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_STORMS_GROTTO_FISH, lambda bundle: has_bottle(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GRASS_1, lambda bundle: can_cut_shrubs(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GRASS_2, lambda bundle: can_cut_shrubs(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GRASS_3, lambda bundle: can_cut_shrubs(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GRASS_4, lambda bundle: can_cut_shrubs(bundle)),
        (Locations.RC_KF_STORMS_GROTTO_GOSSIP_STONE, lambda bundle: True_()),
    ])
    # Exits
    connect_regions(Regions.RR_KF_STORMS_GROTTO, world, [
        (Regions.RR_KF_OUTSIDE_LOST_WOODS, lambda bundle: True_()),
    ])

    # Kokiri Forest
    # Events
    add_events(Regions.RR_KOKIRI_FOREST, world, [
        (EventLocations.RR_KOKIRI_FOREST_LOGIC_FAIRY_ACCESS, Events.LOGIC_FAIRY_ACCESS, lambda bundle: call_gossip_fairy_except_suns(bundle) | is_child(bundle) & can_use(bundle, Items.RG_MAGIC_BEAN) & has_item(bundle, Items.RG_KOKIRI_FOREST_BEAN_SOUL) & can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (EventLocations.RR_KOKIRI_FOREST_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, lambda bundle: is_child(bundle) & has_item(bundle, Items.RG_SPEAK_KOKIRI) & can_use(bundle, Items.RG_KOKIRI_SWORD) & can_use(bundle, Items.RG_DEKU_SHIELD)),
    ])
    # Locations
    add_locations(Regions.RR_KOKIRI_FOREST, world, [
        (Locations.RC_KF_BEAN_SPROUT_FAIRY_1, lambda bundle: is_child(bundle) & can_use(bundle, Items.RG_MAGIC_BEAN) & has_item(bundle, Items.RG_KOKIRI_FOREST_BEAN_SOUL) & can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_BEAN_SPROUT_FAIRY_2, lambda bundle: is_child(bundle) & can_use(bundle, Items.RG_MAGIC_BEAN) & has_item(bundle, Items.RG_KOKIRI_FOREST_BEAN_SOUL) & can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_BEAN_SPROUT_FAIRY_3, lambda bundle: is_child(bundle) & can_use(bundle, Items.RG_MAGIC_BEAN) & has_item(bundle, Items.RG_KOKIRI_FOREST_BEAN_SOUL) & can_use(bundle, Items.RG_SONG_OF_STORMS)),
        (Locations.RC_KF_BRIDGE_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_BEHIND_MIDOS_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_SOUTH_GRASS_WEST_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_SOUTH_GRASS_EAST_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_NORTH_GRASS_WEST_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_NORTH_GRASS_EAST_RUPEE, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_SARIAS_ROOF_WEST_HEART, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_SARIAS_ROOF_EAST_HEART, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_SARIAS_ROOF_NORTH_HEART, lambda bundle: is_child(bundle)),
        (Locations.RC_KF_BEAN_RUPEE_1, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RUPEE_2, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RUPEE_3, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RUPEE_4, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RUPEE_5, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RUPEE_6, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_BEAN_RED_RUPEE, lambda bundle: is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_use(bundle, Items.RG_HOVER_BOOTS) | can_use(bundle, Items.RG_BOOMERANG))),
        (Locations.RC_KF_GS_KNOW_IT_ALL_HOUSE, lambda bundle: is_child(bundle) & can_kill(bundle, Enemies.RE_GOLD_SKULLTULA, EnemyDistance.ED_CLOSE, True, 1, False, False) & can_get_night_time_gs(bundle)),
        (Locations.RC_KF_GS_BEAN_PATCH, lambda bundle: can_spawn_soil_skull(bundle, Items.RG_KOKIRI_FOREST_BEAN_SOUL) & can_kill(bundle, Enemies.RE_GOLD_SKULLTULA, EnemyDistance.ED_CLOSE, True, 1, False, False)),
        (Locations.RC_KF_GS_HOUSE_OF_TWINS, lambda bundle: is_adult(bundle) & can_get_night_time_gs(bundle) & (can_get_drop(bundle, Enemies.RE_GOLD_SKULLTULA, EnemyDistance.ED_BOOMERANG, False) | can_do_trick(bundle, Tricks.RT_KF_ADULT_GS) & can_use(bundle, Items.RG_HOVER_BOOTS) & can_kill(bundle, Enemies.RE_GOLD_SKULLTULA, EnemyDistance.ED_SHORT_JUMPSLASH, True, 1, False, False))),
        (Locations.RC_KF_CHILD_GRASS_1, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_2, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_3, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_4, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_5, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_6, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_7, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_8, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_9, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_10, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_11, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_CHILD_GRASS_12, lambda bundle: is_child(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_1, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_2, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_3, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_4, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_5, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_6, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_7, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_8, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_9, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_10, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_11, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_12, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_13, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_14, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_15, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_16, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_17, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_18, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_19, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
        (Locations.RC_KF_ADULT_GRASS_20, lambda bundle: is_adult(bundle) & can_cut_shrubs(bundle)),
    ])
    # Exits
    connect_regions(Regions.RR_KOKIRI_FOREST, world, [
        (Regions.RR_KF_BOULDER_LOOP, lambda bundle: can_use(bundle, Items.RG_CRAWL)),
        (Regions.RR_KF_LINKS_PORCH, lambda bundle: can_climb_ladder(bundle) if is_child(bundle) else has_item(bundle, Items.RG_CLIMB) | can_use(bundle, Items.RG_HOVER_BOOTS)),
        (Regions.RR_KF_MIDOS_HOUSE, lambda bundle: True_()),
        (Regions.RR_KF_SARIAS_HOUSE, lambda bundle: True_()),
        (Regions.RR_KF_HOUSE_OF_TWINS, lambda bundle: True_()),
        (Regions.RR_KF_KNOW_IT_ALL_HOUSE, lambda bundle: True_()),
        (Regions.RR_KF_KOKIRI_SHOP, lambda bundle: True_()),
        (Regions.RR_KF_OUTSIDE_DEKU_TREE, lambda bundle: has_item(bundle, Events.LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD) | (OptionFilter(RSK_FOREST, RandomizerSettingKey.RO_CLOSED_FOREST_OFF)) | is_adult(bundle) & (can_pass(bundle, Enemies.RE_BIG_SKULLTULA, EnemyDistance.ED_CLOSE, True) | has_item(bundle, Events.LOGIC_FOREST_TEMPLE_CLEAR))),
        (Regions.RR_KF_OUTSIDE_LOST_WOODS, lambda bundle: has_item(bundle, Items.RG_CLIMB) | can_use(bundle, Items.RG_HOOKSHOT) | is_adult(bundle) & (can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL) | can_do_trick(bundle, Tricks.RT_UNINTUITIVE_JUMPS))),
        (Regions.RR_KF_RUPEE_ALCOVE, lambda bundle: is_adult(bundle) & can_plant_bean(bundle, Regions.RR_KOKIRI_FOREST, Items.RG_KOKIRI_FOREST_BEAN_SOUL)),
        (Regions.RR_LW_BRIDGE_FROM_FOREST, lambda bundle: is_adult(bundle) | (OptionFilter(RSK_FOREST, RandomizerSettingKey.RO_CLOSED_FOREST_ON, "ne")) | has_item(bundle, Events.LOGIC_DEKU_TREE_CLEAR)),
    ])

    # Minuet of Forest Warp
    # Exits
    connect_regions(Regions.RR_MINUET_OF_FOREST_WARP, world, [
        (Regions.RR_SACRED_FOREST_MEADOW, lambda bundle: True_()),
    ])

    # Nocturne of Shadow Warp
    # Exits
    connect_regions(Regions.RR_NOCTURNE_OF_SHADOW_WARP, world, [
        (Regions.RR_GRAVEYARD_WARP_PAD_REGION, lambda bundle: True_()),
    ])

    # Prelude of Light Warp
    # Exits
    connect_regions(Regions.RR_PRELUDE_OF_LIGHT_WARP, world, [
        (Regions.RR_TEMPLE_OF_TIME, lambda bundle: True_()),
    ])

    # Requiem of Spirit Warp
    # Exits
    connect_regions(Regions.RR_REQUIEM_OF_SPIRIT_WARP, world, [
        (Regions.RR_DESERT_COLOSSUS, lambda bundle: True_()),
    ])

    # Root
    # Events
    add_events(Regions.RR_ROOT, world, [
        (EventLocations.RR_ROOT_LOGIC_KAKARIKO_GATE_OPEN, Events.LOGIC_KAKARIKO_GATE_OPEN, lambda bundle: OptionFilter(RSK_KAK_GATE, RandomizerSettingKey.RO_KAK_GATE_OPEN)),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER, Events.LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER, lambda bundle: OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FREE)),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER, Events.LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER, lambda bundle: (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FREE)) | (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FAST))),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER, Events.LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER, lambda bundle: (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FREE)) | (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FAST))),
        (EventLocations.RR_ROOT_LOGIC_TH_COULD_FREE_SLOPE_CARPENTER, Events.LOGIC_TH_COULD_FREE_SLOPE_CARPENTER, lambda bundle: (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FREE)) | (OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FAST))),
        (EventLocations.RR_ROOT_LOGIC_TH_RESCUED_ALL_CARPENTERS, Events.LOGIC_TH_RESCUED_ALL_CARPENTERS, lambda bundle: OptionFilter(RSK_GERUDO_FORTRESS, RandomizerSettingKey.RO_GF_CARPENTERS_FREE)),
        (EventLocations.RR_ROOT_LOGIC_FREED_EPONA, Events.LOGIC_FREED_EPONA, lambda bundle: OptionFilter(RSK_SKIP_EPONA_RACE, RandomizerSettingKey.RO_GENERIC_YES)),
    ])
    # Locations
    add_locations(Regions.RR_ROOT, world, [
        (Locations.RC_LINKS_POCKET, lambda bundle: True_()),
        (Locations.RC_TRIFORCE_COMPLETED, lambda bundle: CanWinTriforceHunt()),
        (Locations.RC_SARIA_SONG_HINT, lambda bundle: can_use(bundle, Items.RG_SARIAS_SONG)),
        (Locations.RC_SONG_FROM_IMPA, lambda bundle: OptionFilter(RSK_SKIP_CHILD_ZELDA, RandomizerSettingKey.RO_GENERIC_YES)),
        (Locations.RC_HC_MALON_EGG, lambda bundle: OptionFilter(RSK_SKIP_CHILD_ZELDA, RandomizerSettingKey.RO_GENERIC_YES)),
        (Locations.RC_HC_ZELDAS_LETTER, lambda bundle: OptionFilter(RSK_SKIP_CHILD_ZELDA, RandomizerSettingKey.RO_GENERIC_YES)),
        (Locations.RC_TOT_MASTER_SWORD, lambda bundle: OptionFilter(RSK_SELECTED_STARTING_AGE, RandomizerSettingKey.RO_AGE_ADULT)),
    ])
    # Exits
    connect_regions(Regions.RR_ROOT, world, [
        (Regions.RR_ROOT_EXITS, lambda bundle: True_()),
    ])

    # Root Exits
    # Exits
    connect_regions(Regions.RR_ROOT_EXITS, world, [
        (Regions.RR_CHILD_SPAWN, lambda bundle: is_child(bundle)),
        (Regions.RR_ADULT_SPAWN, lambda bundle: is_adult(bundle)),
        (Regions.RR_MINUET_OF_FOREST_WARP, lambda bundle: can_use(bundle, Items.RG_MINUET_OF_FOREST)),
        (Regions.RR_BOLERO_OF_FIRE_WARP, lambda bundle: can_use(bundle, Items.RG_BOLERO_OF_FIRE)),
        (Regions.RR_SERENADE_OF_WATER_WARP, lambda bundle: can_use(bundle, Items.RG_SERENADE_OF_WATER)),
        (Regions.RR_NOCTURNE_OF_SHADOW_WARP, lambda bundle: can_use(bundle, Items.RG_NOCTURNE_OF_SHADOW)),
        (Regions.RR_REQUIEM_OF_SPIRIT_WARP, lambda bundle: can_use(bundle, Items.RG_REQUIEM_OF_SPIRIT)),
        (Regions.RR_PRELUDE_OF_LIGHT_WARP, lambda bundle: can_use(bundle, Items.RG_PRELUDE_OF_LIGHT)),
    ])

    # Serenade of Water Warp
    # Exits
    connect_regions(Regions.RR_SERENADE_OF_WATER_WARP, world, [
        (Regions.RR_LAKE_HYLIA, lambda bundle: True_()),
    ])

