#include "helpers.h"

using namespace rls::transpilers::soh_tests;

TEST(SohSolverTests, GenerateFunctionSimpleDefinitions) {
	const auto project = resolveFromSource(
		"define invert(value: Bool):\n"
		"    not value\n"
		"\n"
		"define add(a: Int, b: Int):\n"
		"    a + b\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsSource(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"int add(const int a, const int b);\n"
		"bool invert(const bool value);\n"
	);

	EXPECT_EQ(out.content("functions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"functions.gen.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"int add(const int a, const int b) {\n"
		"    return a + b;\n"
		"}\n"
		"\n"
		"bool invert(const bool value) {\n"
		"    return !value;\n"
		"}\n"
	);
}