#include "helpers.h"

using namespace rls::transpilers::soh_tests;

TEST(SohSolverTests, GenerateRegionSimple) {
    const auto project = resolveFromSource (
        "define kill_fn(e: Enemy, distance = ED_CLOSE):\n"
        "    always\n"
        "\n"
        "define call_gossip_fairy_except_suns():\n"
        "    can_use(RG_ZELDAS_LULLABY) or\n"
        "    can_use(RG_EPONAS_SONG) or\n"
        "    can_use(RG_SONG_OF_TIME)\n"
        "\n"
        "define call_gossip_fairy():\n"
        "    call_gossip_fairy_except_suns() or can_use(RG_SUNS_SONG)\n"
        "\n"
        "define can_bonk_trees():\n"
        "    always\n"
        "\n"
        "region RR_HC_GATE {\n"
        "    name: \"Hyrule Castle Gate\"\n"
        "    scene: SCENE_HYRULE_CASTLE\n"
        "    events {\n"
        "        LOGIC_FAIRY_ACCESS: call_gossip_fairy() or can_use(RG_STICKS)\n"
        "        LOGIC_BUG_ACCESS: has(RG_POWER_BRACELET)\n"
        "    }\n"
        "    locations {\n"
        "        RC_HC_MALON_EGG: has(RG_SPEAK_HYLIAN)\n"
        "        RC_HC_GS_TREE: can_bonk_trees() and kill_fn(RE_GOLD_SKULLTULA, ED_CLOSE)\n"
        "        RC_HC_SKULLTULA_TREE: can_bonk_trees()\n"
        "    }\n"
        "    exits {\n"
        "        RR_CASTLE_GROUNDS: always\n"
        "        RR_HC_ABOVE_VINE: has(RG_CLIMB) or can_use(RG_HOOKSHOT)\n"
        "        RR_HC_PAST_GATE: has(RG_CHILD_WALLET) and has(RG_SPEAK_HYLIAN)\n"
        "    }\n"
        "}"
    );

    MemoryWriter out;
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsHeader(out);
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);

	EXPECT_EQ(out.content("regions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"void RegisterRegions();\n"
	);

	EXPECT_EQ(out.content("regions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"regions.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"void RegisterRegions() {\n"
        "\n"
        "areaTable[RR_HC_GATE] = Region(\"Hyrule Castle Gate\", SCENE_HYRULE_CASTLE, {\n"
        "    // Events\n"
        "    EVENT_ACCESS(LOGIC_FAIRY_ACCESS, call_gossip_fairy() || can_use(RG_STICKS)),\n"
        "    EVENT_ACCESS(LOGIC_BUG_ACCESS, has(RG_POWER_BRACELET)),\n"
        "}, {\n"
        "    // Locations\n"
        "    LOCATION(RC_HC_MALON_EGG, has(RG_SPEAK_HYLIAN)),\n"
        "    LOCATION(RC_HC_GS_TREE, can_bonk_trees() && kill_fn(RE_GOLD_SKULLTULA, ED_CLOSE)),\n"
        "    LOCATION(RC_HC_SKULLTULA_TREE, can_bonk_trees()),\n"
        "}, {\n"
        "    // Exits\n"
        "    ENTRANCE(RR_CASTLE_GROUNDS, true),\n"
        "    ENTRANCE(RR_HC_ABOVE_VINE, has(RG_CLIMB) || can_use(RG_HOOKSHOT)),\n"
        "    ENTRANCE(RR_HC_PAST_GATE, has(RG_CHILD_WALLET) && has(RG_SPEAK_HYLIAN)),\n"
        "});\n"
        "\n"
        "}\n"
	);
}