#include "helpers.h"

using namespace rls::transpilers::soh_tests;

TEST(SohSolverTests, GenerateFunctionSimpleDefinitions) {
	const auto project = resolveFromSource(
		"define invert(value: Bool):\n"
		"    not value\n"
		"\n"
		"define add(a: Int, b: Int):\n"
		"    a + b\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsSource(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"int add(const int a, const int b);\n"
		"bool invert(const bool value);\n"
	);

	EXPECT_EQ(out.content("functions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"functions.gen.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"int add(const int a, const int b) {\n"
		"    return a + b;\n"
		"}\n"
		"\n"
		"bool invert(const bool value) {\n"
		"    return !value;\n"
		"}\n"
	);
}

TEST(SohSolverTests, GenerateFunctionDefinitionWithInferredDistanceParam) {
	const auto project = resolveFromSource(
		"define distance_to_int(distance):\n"
		"    match distance {\n"
		"        ED_CLOSE: 0\n"
		"        ED_FAR: 8\n"
		"    }\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"int distance_to_int(const EnemyDistance distance);\n"
	);
}

TEST(SohSolverTests, GenerateFunctionDefinitionWithInferredBoolParam) {
	const auto project = resolveFromSource(
		"define _can_kill_gold_skulltula(distance, wall_or_floor):\n"
		"    match distance {\n"
		"        ED_LONGSHOT: wall_or_floor and can_use(RG_BOMBCHU_5)\n"
		"        _: can_use(RG_FAIRY_BOW)\n"
		"    }\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"bool _can_kill_gold_skulltula(const EnemyDistance distance, const bool wall_or_floor);\n"
	);
}

TEST(SohSolverTests, GenerateFunctionWithDefaultParam) {
	const auto project = resolveFromSource(
		"define double(a = 2):\n"
		"    a * 2\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsSource(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"int double(const int a = 2);\n"
	);

	EXPECT_EQ(out.content("functions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"functions.gen.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"int double(const int a) {\n"
		"    return a * 2;\n"
		"}\n"
	);
}

TEST(SohSolverTests, GenerateFunctionHeaderEmitsNormalEnumDefinition) {
	const auto project = resolveFromSource(
		"enum Color { RED, GREEN = 1 }\n"
		"define get_color():\n"
		"    RED\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"enum class Color : int {\n"
		"    RED = 0,\n"
		"    GREEN = 1\n"
		"};\n"
		"\n"
		"Color get_color();\n"
	);
}

TEST(SohSolverTests, GenerateFunctionWithEnumReturnType) {
	const auto project = resolveFromSource(
		"enum Color { RED }\n"
		"define get_color():\n"
		"    Color.RED\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsSource(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"enum class Color : int {\n"
		"    RED = 0\n"
		"};\n"
		"\n"
		"Color get_color();\n"
	);

	EXPECT_EQ(out.content("functions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"functions.gen.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"Color get_color() {\n"
		"    return Color::RED;\n"
		"}\n"
	);
}

TEST(SohSolverTests, GenerateFunctionWithEnumParamType) {
	const auto project = resolveFromSource(
		"enum Color { RED, GREEN = 1 }\n"
		"define accepts_color(c: Enum = RED):\n"
		"    c is RED\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"enum class Color : int {\n"
		"    RED = 0,\n"
		"    GREEN = 1\n"
		"};\n"
		"\n"
		"bool accepts_color(const Color c = Color::RED);\n"
	);
}

TEST(SohSolverTests, GenerateFunctionWithUnidentifiedEnumParamUsesInt) {
	const auto project = resolveFromSource(
		"define passthrough(value: Enum):\n"
		"    value\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsSource(out);

	EXPECT_EQ(out.content("functions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include <functional>\n"
		"#include \"soh/Enhancements/randomizer/location_access.h\"\n"
		"#include \"soh/Enhancements/randomizer/entrance.h\"\n"
		"#include \"rls_match.h\"\n"
		"#include \"rls_host.h\"\n"
		"\n"
		"int passthrough(const int value);\n"
	);

	EXPECT_EQ(out.content("functions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"functions.gen.h\"\n"
		"#include \"rls_match.h\"\n"
		"\n"
		"int passthrough(const int value) {\n"
		"    return value;\n"
		"}\n"
	);
}

TEST(SohSolverTests, GenerateFunctionWithDomainValueParams) {
	auto project = resolveFromSource(
		"define uses_domain(reg: Region, evt: Event, loc: Location): true\n");
	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateFunctionDefinitionsHeader(out);

	EXPECT_NE(out.content("functions.gen.h").find(
		"bool uses_domain(const RandomizerRegion reg, const LogicVal evt, "
		"const RandomizerCheck loc);"), std::string::npos);
}