#include "helpers.h"

using namespace rls::transpilers::soh_tests;

// == Kill-only enemy (pass/avoid default to true, drop falls through to default) =

TEST(SohEnemies, KillOnlyEnemy) {
	const auto project = resolveFromSource(
		"enemy RE_IRON_KNUCKLE {\n"
		"    kill: can_use_sword() or can_use(RG_MEGATON_HAMMER) or has_explosives()\n"
		"}\n"
		"define can_use_sword(): can_use(RG_KOKIRI_SWORD) or can_use(RG_MASTER_SWORD) or can_use(RG_BIGGORON_SWORD)\n"
		"define has_explosives(): has(RG_BOMB_BAG) or has(RG_BOMBCHU_5)\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_IRON_KNUCKLE:\n"
		"            return can_use_sword() || can_use(RG_MEGATON_HAMMER) || has_explosives();\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}

// == Enemy with explicit pass: never =========================================

TEST(SohEnemies, ExplicitPassField) {
	const auto project = resolveFromSource(
		"enemy RE_IRON_KNUCKLE {\n"
		"    kill: can_use(RG_MASTER_SWORD)\n"
		"    pass: never\n"
		"}\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_IRON_KNUCKLE:\n"
		"            return can_use(RG_MASTER_SWORD);\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        case RE_IRON_KNUCKLE:\n"
		"            return false;\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}

// == Enemy with all 4 fields =================================================

TEST(SohEnemies, AllFieldsExplicit) {
	const auto project = resolveFromSource(
		"enemy RE_BEAMOS {\n"
		"    kill: has_explosives()\n"
		"    pass: always\n"
		"    avoid(grounded = false, quantity = 1):\n"
		"        not grounded or can_use(RG_NUTS)\n"
		"    drop: has_explosives()\n"
		"}\n"
		"define has_explosives(): has(RG_BOMB_BAG) or has(RG_BOMBCHU_5)\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_BEAMOS:\n"
		"            return has_explosives();\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        case RE_BEAMOS:\n"
		"            return true;\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        case RE_BEAMOS:\n"
		"            return !grounded || can_use(RG_NUTS);\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        case RE_BEAMOS:\n"
		"            return has_explosives();\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}

// == Enemy with match distance in kill field =================================

TEST(SohEnemies, KillWithMatchDistance) {
	const auto project = resolveFromSource(
		"enemy RE_KEESE {\n"
		"    kill:\n"
		"        match distance {\n"
		"            ED_CLOSE or\n"
		"            ED_SHORT_JUMPSLASH: can_use(RG_KOKIRI_SWORD) or\n"
		"            ED_HOOKSHOT: can_use(RG_HOOKSHOT) or\n"
		"            ED_FAR: can_use(RG_FAIRY_BOW)\n"
		"        }\n"
		"}\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_KEESE:\n"
		"            return rls::match([&]{return distance == ED_CLOSE || distance == ED_SHORT_JUMPSLASH;}, [&]{return can_use(RG_KOKIRI_SWORD);}, true, [&]{return distance == ED_HOOKSHOT;}, [&]{return can_use(RG_HOOKSHOT);}, true, [&]{return distance == ED_FAR;}, [&]{return can_use(RG_FAIRY_BOW);}, false);\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}

// == Multiple enemies sorted alphabetically ==================================

TEST(SohEnemies, MultipleEnemies) {
	const auto project = resolveFromSource(
		"enemy RE_ARMOS {\n"
		"    kill: can_use(RG_MEGATON_HAMMER)\n"
		"}\n"
		"enemy RE_DODONGO {\n"
		"    kill: can_use(RG_MASTER_SWORD)\n"
		"}\n"
		"enemy RE_KEESE {\n"
		"    kill: can_use(RG_KOKIRI_SWORD)\n"
		"}\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_ARMOS:\n"
		"            return can_use(RG_MEGATON_HAMMER);\n"
		"        case RE_DODONGO:\n"
		"            return can_use(RG_MASTER_SWORD);\n"
		"        case RE_KEESE:\n"
		"            return can_use(RG_KOKIRI_SWORD);\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}

// == Header generation =======================================================

TEST(SohEnemies, GenerateHeader) {
	const auto project = resolveFromSource(
		"enemy RE_ARMOS {\n"
		"    kill: can_use(RG_MEGATON_HAMMER)\n"
		"}\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesHeader(out);

	EXPECT_EQ(out.content("enemies.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"#include \"soh/Enhancements/randomizer/logic.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance = ED_CLOSE, bool wallOrFloor = true, uint8_t quantity = 1, bool timer = false, bool inWater = false);\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance = ED_CLOSE, bool wallOrFloor = true);\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded = false, uint8_t quantity = 1);\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance = ED_CLOSE, bool aboveLink = false);\n"
	);
}

// == Simple enemy with explicit pass: always =================================

TEST(SohEnemies, SimpleEnemyWithExplicitPass) {
	const auto project = resolveFromSource(
		"enemy RE_DODONGO {\n"
		"    kill: can_use(RG_MASTER_SWORD) or has_explosives()\n"
		"    pass: always\n"
		"}\n"
		"define has_explosives(): has(RG_BOMB_BAG) or has(RG_BOMBCHU_5)\n"
	);

	MemoryWriter out;
	rls::transpilers::soh::SohTranspiler(project).GenerateEnemiesSource(out);

	EXPECT_EQ(out.content("enemies.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"enemies.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
		"\n"
		"bool CanKillEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor, uint8_t quantity, bool timer, bool inWater) {\n"
		"    switch (enemy) {\n"
		"        case RE_DODONGO:\n"
		"            return can_use(RG_MASTER_SWORD) || has_explosives();\n"
		"        default:\n"
		"            return false;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanPassEnemy(RandomizerEnemy enemy, EnemyDistance distance, bool wallOrFloor) {\n"
		"    if (CanKillEnemy(enemy, distance, wallOrFloor)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        case RE_DODONGO:\n"
		"            return true;\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanAvoidEnemy(RandomizerEnemy enemy, bool grounded, uint8_t quantity) {\n"
		"    if (CanKillEnemy(enemy, ED_CLOSE, true, quantity)) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return true;\n"
		"    }\n"
		"}\n"
		"\n"
		"bool CanGetEnemyDrop(RandomizerEnemy enemy, EnemyDistance distance, bool aboveLink) {\n"
		"    if (!CanKillEnemy(enemy, distance)) {\n"
		"        return false;\n"
		"    }\n"
		"    if (distance <= ED_MASTER_SWORD_JUMPSLASH) {\n"
		"        return true;\n"
		"    }\n"
		"    switch (enemy) {\n"
		"        default:\n"
		"            return aboveLink || (distance <= ED_BOOMERANG && logic->CanUse(RG_BOOMERANG));\n"
		"    }\n"
		"}\n"
	);
}
