#include "helpers.h"

using namespace rls::transpilers::soh_tests;

TEST(SohSolverTests, GenerateRegionSimple) {
    const auto project = resolveFromSource (
        "define kill_fn(e: Enemy, distance = ED_CLOSE):\n"
        "    always\n"
        "\n"
        "define call_gossip_fairy_except_suns():\n"
        "    can_use(RG_ZELDAS_LULLABY) or\n"
        "    can_use(RG_EPONAS_SONG) or\n"
        "    can_use(RG_SONG_OF_TIME)\n"
        "\n"
        "define call_gossip_fairy():\n"
        "    call_gossip_fairy_except_suns() or can_use(RG_SUNS_SONG)\n"
        "\n"
        "define can_bonk_trees():\n"
        "    always\n"
        "\n"
        "region RR_HC_GATE {\n"
        "    name: \"Hyrule Castle Gate\"\n"
        "    scene: SCENE_HYRULE_CASTLE\n"
		"    unrelatedData: \"ignored by SoH\"\n"
        "    events {\n"
        "        LOGIC_FAIRY_ACCESS: call_gossip_fairy() or can_use(RG_STICKS)\n"
        "        LOGIC_BUG_ACCESS: has(RG_POWER_BRACELET)\n"
        "    }\n"
        "    locations {\n"
        "        RC_HC_MALON_EGG: has(RG_SPEAK_HYLIAN)\n"
        "        RC_HC_GS_TREE: can_bonk_trees() and kill_fn(RE_GOLD_SKULLTULA, ED_CLOSE)\n"
        "        RC_HC_SKULLTULA_TREE: can_bonk_trees()\n"
        "    }\n"
        "    exits {\n"
        "        RR_CASTLE_GROUNDS: always\n"
        "        RR_HC_ABOVE_VINE: has(RG_CLIMB) or can_use(RG_HOOKSHOT)\n"
        "        RR_HC_PAST_GATE: has(RG_CHILD_WALLET) and has(RG_SPEAK_HYLIAN)\n"
        "    }\n"
        "}"
    );

    MemoryWriter out;
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsHeader(out);
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);

	EXPECT_EQ(out.content("regions.gen.h"),
		"// Generated by RLS soh transpiler\n"
		"#pragma once\n"
		"\n"
		"void RegisterRegions();\n"
	);

	EXPECT_EQ(out.content("regions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"regions.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
        "\n"
        "using namespace Rando;\n"
		"\n"
		"void register_tests() {\n"
        "\n"
        "areaTable[RR_HC_GATE] = Region(\"Hyrule Castle Gate\", SCENE_HYRULE_CASTLE, {\n"
        "    // Events\n"
        "    EVENT_ACCESS(LOGIC_FAIRY_ACCESS, call_gossip_fairy() || can_use(RandomizerGet::RG_STICKS)),\n"
        "    EVENT_ACCESS(LOGIC_BUG_ACCESS, has(RandomizerGet::RG_POWER_BRACELET)),\n"
        "}, {\n"
        "    // Locations\n"
        "    LOCATION(RC_HC_MALON_EGG, has(RandomizerGet::RG_SPEAK_HYLIAN)),\n"
        "    LOCATION(RC_HC_GS_TREE, can_bonk_trees() && kill_fn(RandomizerEnemy::RE_GOLD_SKULLTULA, EnemyDistance::ED_CLOSE)),\n"
        "    LOCATION(RC_HC_SKULLTULA_TREE, can_bonk_trees()),\n"
        "}, {\n"
        "    // Exits\n"
        "    ENTRANCE(RR_CASTLE_GROUNDS, true),\n"
        "    ENTRANCE(RR_HC_ABOVE_VINE, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOOKSHOT)),\n"
        "    ENTRANCE(RR_HC_PAST_GATE, has(RandomizerGet::RG_CHILD_WALLET) && has(RandomizerGet::RG_SPEAK_HYLIAN)),\n"
        "});\n"
        "\n"
        "}\n"
        "\n"
        "void RegisterRegions() {\n"
        "    register_tests();\n"
        "}\n"
	);
}

TEST(SohSolverTests, GenerateRegionDecaysIntConditionsToBool) {
    const auto project = resolveFromSource(
        "region RR_TEST {\n"
        "    name: \"Test\"\n"
        "    scene: SCENE_TEST\n"
        "    locations { RC_TEST: hearts() }\n"
        "}\n"
    );

    MemoryWriter out;
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);

    EXPECT_NE(out.content("regions.gen.cpp").find(
        "LOCATION(RC_TEST, hearts() != 0)"), std::string::npos);
}

TEST(SohSolverTests, GenerateRegionUsesExplicitConstructorForRegionMetadata) {
    const auto project = resolveFromSource (
		"enum TimePasses { Auto, Yes, No }\n"
        "region RR_CHILD_SPAWN {\n"
        "    name: \"Child Spawn\"\n"
        "    scene: SCENE_ID_MAX\n"
        "    timePasses: TimePasses.No\n"
        "    areas: [RA_LINKS_POCKET]\n"
        "\n"
        "    exits {\n"
        "        RR_KF_LINKS_HOUSE: always\n"
        "    }\n"
        "}\n"
    );

    MemoryWriter out;
    rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);

	EXPECT_EQ(out.content("regions.gen.cpp"),
		"// Generated by RLS soh transpiler\n"
		"#include \"regions.gen.h\"\n"
		"#include \"functions.gen.h\"\n"
        "\n"
        "using namespace Rando;\n"
		"\n"
		"void register_tests() {\n"
        "\n"
        "areaTable[RR_CHILD_SPAWN] = Region(\"Child Spawn\", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {\n"
        "    // Events\n"
        "}, {\n"
        "    // Locations\n"
        "}, {\n"
        "    // Exits\n"
        "    ENTRANCE(RR_KF_LINKS_HOUSE, true),\n"
        "});\n"
        "\n"
        "}\n"
        "\n"
        "void RegisterRegions() {\n"
        "    register_tests();\n"
        "}\n"
	);
}

TEST(SohSolverTests, GenerateRegionRequiresSohMetadata) {
    const auto project = resolveFromSource(
        "region RR_TEST {\n"
        "    scene: SCENE_TEST\n"
        "}\n"
    );

    MemoryWriter out;
    const auto diagnostics =
        rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);
    ASSERT_EQ(diagnostics.size(), 1u);
    EXPECT_EQ(diagnostics[0].level, rls::ast::DiagnosticLevel::Error);
    EXPECT_EQ(diagnostics[0].message,
        "region 'RR_TEST' requires SoH data key 'name'");
    EXPECT_TRUE(out.content("regions.gen.cpp").empty());
}

TEST(SohSolverTests, GenerateRegionRejectsNonAreaListValues) {
    const auto project = resolveFromSource(
        "region RR_TEST {\n"
        "    name: \"Test\"\n"
        "    scene: SCENE_TEST\n"
        "    areas: [RG_HOOKSHOT]\n"
        "}\n"
    );

    MemoryWriter out;
    const auto diagnostics =
        rls::transpilers::soh::SohTranspiler(project).GenerateRegionsSource(out);
    ASSERT_EQ(diagnostics.size(), 1u);
    EXPECT_EQ(diagnostics[0].level, rls::ast::DiagnosticLevel::Error);
    EXPECT_EQ(diagnostics[0].message,
        "region 'RR_TEST' data key 'areas' must contain only Area enum values");
    EXPECT_TRUE(out.content("regions.gen.cpp").empty());
}

TEST(SohSolverTests, TranspilePreflightSkipsAllOutputOnMetadataError) {
    const auto project = resolveFromSource(
        "region RR_TEST {\n"
        "    scene: SCENE_TEST\n"
        "}\n"
    );

    MemoryWriter out;
    const auto diagnostics = rls::transpilers::soh::SohTranspiler(project).Transpile(out);
    ASSERT_EQ(diagnostics.size(), 1u);
    EXPECT_EQ(diagnostics[0].message,
        "region 'RR_TEST' requires SoH data key 'name'");
    EXPECT_TRUE(out.buffers.empty());
}