#include "soh_ap.h"
#include "generate_regions.cpp"

#include <functional>
#include <sstream>

namespace rls::transpilers::soh_ap {

void WriteEventLocations(
	const SohApTranspiler& transpiler,
	std::ostream& source,
    std::string region,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "    " << region << "_" << entry.name << " = auto()\n";
    });
}

void WriteEvents(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "    " << entry.name << " = auto()\n";
    });
}

void WriteLocationsEnum(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Locations, [&](const rls::ast::Entry& entry){
        source << "    " << entry.name << " = auto()\n";
    });
}

void SohApTranspiler::GenerateEnumsSource(rls::OutputWriter& out) const {    
    auto& source = out.open("enums.gen.py");

    source 
        << "# Generated by RLS soh_ap transpiler\n"
        << "from enum import StrEnum, IntEnum, auto, Enum\n";
        
    std::ostringstream eventLocations;
    std::ostringstream events;
    std::ostringstream regions;
    std::ostringstream locations;

    eventLocations << "class EventLocations(StrEnum):\n";
    events << "class Events(StrEnum):\n";
    regions << "class RandomizerRegions(StrEnum):\n";;
    locations << "class RandomizerChecks(StrEnum):\n";;

    for (const auto& [regionName, region] : project.RegionDecls) {
        // Do Regions while here
        regions << "    " << region->key.text << " = \"" << region->body.name << "\"\n";

        std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
        const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

        if (extendRegionIt != project.ExtendRegionDecls.end()) {
            extendRegionDecls = extendRegionIt->second;
        }

        // Event Locations
        WriteEventLocations(*this, eventLocations, region->key.text, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEventLocations(*this, eventLocations, region->key.text, extendRegion->sections);
        }

        // Events
        WriteEvents(*this, events, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEvents(*this, events, extendRegion->sections);
        }

        // Locations
        WriteLocationsEnum(*this, locations, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteLocationsEnum(*this, locations, extendRegion->sections);
        }
    }

    // Output to source
    source << "\n" << eventLocations.str();
    source << "\n" << events.str();
    source << "\n" << regions.str();
    source << "\n" << locations.str();

}

} // namespace rls::transpilers::soh_ap