#include "soh_ap.h"
#include "generate_regions.cpp"

#include <functional>
#include <sstream>

namespace rls::transpilers::soh_ap {

void WriteEventLocations(
	const SohApTranspiler& transpiler,
	std::ostream& source,
    std::string region,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "    " << region << "_" << entry.name << " = auto()\n";
    });
}

void WriteEvents(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "    " << entry.name << " = auto()\n";
    });
}

void SohApTranspiler::GenerateEnumsSource(rls::OutputWriter& out) const {    
    auto& source = out.open("enums.gen.py");

    std::stringstream sstream;

    sstream << "class RandomizerRegions(StrEnum):\n";

    source 
        << "# Generated by RLS soh_ap transpiler\n"
        << "from enum import StrEnum, IntEnum, auto, Enum\n"
        << "\n"
        << "class EventLocations(StrEnum):\n";

    // Event Locations
    for (const auto& [regionName, region] : project.RegionDecls) {
        // Do Regions while here
        sstream << "    " << region->key.text << " = \"" << region->body.name << "\"\n";

        std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
        const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

        if (extendRegionIt != project.ExtendRegionDecls.end()) {
            extendRegionDecls = extendRegionIt->second;
        }

        WriteEventLocations(*this, source, region->key.text, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEventLocations(*this, source, region->key.text, extendRegion->sections);
        }
    }

    // Events
    source 
        << "\n"
        << "class Events(StrEnum):\n";
    for (const auto& [regionName, region] : project.RegionDecls) {
        std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
        const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

        if (extendRegionIt != project.ExtendRegionDecls.end()) {
            extendRegionDecls = extendRegionIt->second;
        }

        WriteEvents(*this, source, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEvents(*this, source, extendRegion->sections);
        }
    }
    
    // Regions
    source << "\n" << sstream.str();

}

} // namespace rls::transpilers::soh_ap