#include "soh_ap.h"

#include <sstream>

using AT = rls::ast::Type;

namespace rls::transpilers::soh_ap {

template <typename T>
std::string nodeType(const rls::ast::Project& p, const T* node) {
    const auto type = p.getType(node);
    if (!type.has_value()) {
        return "missing_type";
    }

    switch (type.value()) {
        case AT::Bool: return "bool";
        case AT::Int: return "int";
        case AT::Item: return "RandomizerGet";
        case AT::Enemy: return "RandomizerEnemy";
        case AT::Distance: return "EnemyDistance";
        case AT::Trick: return "RandomizerTrick";
        case AT::Setting: return "RandomizerSettingKey";
        case AT::Region: return "RandomizerRegion";
        case AT::Check: return "RandomizerCheck";
        case AT::Logic: return "LogicVal";
        case AT::Scene: return "SceneID";
        case AT::Dungeon: return "DungeonKey";
        case AT::Area: return "RandomizerArea";
        case AT::Trial: return "TrialKey";
        case AT::WaterLevel: return "RandoWaterLeve";
        default: return "unsupported_type";
    }
}

std::string functionSignature(
	const SohApTranspiler& transpiler,
	const rls::ast::Project& p,
	const rls::ast::DefineDecl* decl,
    const bool includeDefaults)
{
    std::ostringstream sig;
    sig << "def " << decl->name << "(";
    for (int i = 0; i < decl->params.size(); i++) {
        const auto& param = decl->params[i];
        sig << param.name << ": " << nodeType(p, &param);
        if (includeDefaults && param.defaultValue != nullptr) {
			sig << " = " + transpiler.GenerateExpression(param.defaultValue);
        }
        if (i < decl->params.size() - 1) {
            sig << ", ";
        }
    }
    sig << ") -> " << nodeType(p, decl->body.get()) ;
    return sig.str();
}

void SohApTranspiler::GenerateFunctionDefinitionsSource(rls::OutputWriter& out) const {
    auto& source = out.open("functions.gen.py");
    source << "# Generated by RLS soh_ap transpiler\n\n"
           << "from .Enums import *\n";


    for (const auto& [name, decl] : project.DefineDecls) {
        source << "\n";
        
        source << functionSignature(*this, project, decl, false) << ":\n";
		source << "    return " << GenerateExpression(decl->body) << "\n";
    }
}

}