#include "soh_ap.h"

#include <functional>
#include <sstream>

namespace rls::transpilers::soh_ap {

using EntryWriter = std::function<void(const rls::ast::Entry&)>;
void WriteEntries(const std::vector<rls::ast::Section>& sections,
    rls::ast::SectionKind sectionKind, EntryWriter writer) {
    for (const auto& section : sections) {
        if (section.kind == sectionKind) {
            for (const auto& entry : section.entries) {
                writer(entry);
            }
        }
    }
}

void WriteEvents(
	const SohApTranspiler& transpiler,
	std::ostream& source,
    std::string region,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "        (EventLocations." << region << "_" << entry.name << ", Events." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteLocations(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Locations, [&](const rls::ast::Entry& entry){
        source << "        (Locations." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteExits(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Exits, [&](const rls::ast::Entry& entry){
        source << "        (Regions." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void SohApTranspiler::GenerateRegionsSource(rls::OutputWriter& out) const {    
    auto& source = out.open("regions.gen.py");
    source 
        << "# Generated by RLS soh_ap transpiler\n"
        << "from .LogicHelpers import *\n"
        << "\n"
        << "if TYPE_CHECKING:\n"
        << "    from ... import SohWorld\n"
        << "\n"
        << "def set_region_rules(world: \"SohWorld\") -> None:\n";

    std::ostringstream events;
    std::ostringstream locations;
    std::ostringstream exits;

    for (const auto& [regionName, region] : project.RegionDecls) {
        const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

        std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
        if (extendRegionIt != project.ExtendRegionDecls.end()) {
            extendRegionDecls = extendRegionIt->second;
        }

        std::string creationString = "Regions." + region->key.text + ", world, [\n";

        source << "    # " << region->body.name << "\n";
        events 
            << "    # Events\n"
            << "    add_events(" << creationString;

        WriteEvents(*this, events, region->key.text, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEvents(*this, events, region->key.text, extendRegion->sections);
        }
        
        events << "    ])\n";

        if (events.str() == "    # Events\n    add_events(" + creationString + "    ])\n") {
            events.str("");
        }

        locations 
            << "    # Locations\n"
            << "    add_locations(" << creationString;

        WriteLocations(*this, locations, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteLocations(*this, locations, extendRegion->sections);
        }

        locations << "    ])\n";

        if (locations.str() == "    # Locations\n    add_locations(" + creationString + "    ])\n") {
            locations.str("");
        }


        exits 
            << "    # Exits\n"
            << "    connect_regions(" << creationString;

        WriteExits(*this, exits, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteExits(*this, exits, extendRegion->sections);
        }

        exits << "    ])\n";

        if (exits.str() == "    # Exits\n    connect_regions(" + creationString + "    ])\n") {
            exits.str("");
        }

        // Add things to source
        source << events.str();
        source << locations.str();
        source << exits.str();
        source << "\n";

        // Clear ostringstreams
        events.str("");
        locations.str("");
        exits.str("");
    }
}

} // namespace rls::transpilers::soh_ap