#include "soh_ap.h"

#include <functional>

namespace rls::transpilers::soh_ap {

using EntryWriter = std::function<void(const rls::ast::Entry&)>;
void WriteEntries(const std::vector<rls::ast::Section>& sections,
    rls::ast::SectionKind sectionKind, EntryWriter writer) {
    for (const auto& section : sections) {
        if (section.kind == sectionKind) {
            for (const auto& entry : section.entries) {
                writer(entry);
            }
        }
    }
}

void WriteEvents(
	const SohApTranspiler& transpiler,
	std::ostream& source,
    std::string region,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "        (EventLocations." << region << "_" << entry.name << ", Events." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteLocations(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Locations, [&](const rls::ast::Entry& entry){
        source << "        (RandomizerCheck." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteExits(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Exits, [&](const rls::ast::Entry& entry){
        source << "        (RandomizerRegion." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void SohApTranspiler::GenerateRegionsSource(rls::OutputWriter& out) const {    
    auto& source = out.open("regions.gen.py");
    source 
        << "# Generated by RLS soh_ap transpiler\n"
        << "from .functions.gen.py import *\n"
        << "\n"
        << "if TYPE_CHECKING:\n"
        << "    from ... import SohWorld\n"
        << "\n"
        << "def set_region_rules(world: \"SohWorld\") -> None:\n";

    for (const auto& [regionName, region] : project.RegionDecls) {
        const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

        std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
        if (extendRegionIt != project.ExtendRegionDecls.end()) {
            extendRegionDecls = extendRegionIt->second;
        }

        std::string creationString = "Regions." + region->key.text + ", world, [\n";

        source 
            << "    # " << region->body.name << "\n"
            << "    # Events\n";

        source << "    add_events(" << creationString;
        WriteEvents(*this, source, region->key.text, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteEvents(*this, source, region->key.text, extendRegion->sections);
        }
        source 
            << "    ])\n    # Locations\n"
            << "    add_locations(" << creationString;
        WriteLocations(*this, source, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteLocations(*this, source, extendRegion->sections);
        }
        source 
            << "    ])\n    # Exits\n"
            << "    connect_regions(" << creationString;
        WriteExits(*this, source, region->body.sections);
        for (const auto* extendRegion : extendRegionDecls) {
            WriteExits(*this, source, extendRegion->sections);
        }
        source << "    ])\n\n";
    }
}

} // namespace rls::transpilers::soh_ap