#include "soh_ap.h"

#include <functional>
#include <string>

namespace rls::transpilers::soh_ap {

using EntryWriter = std::function<void(const rls::ast::Entry&)>;
void WriteEntries(const std::vector<rls::ast::Section>& sections,
    rls::ast::SectionKind sectionKind, EntryWriter writer) {
    for (const auto& section : sections) {
        if (section.kind == sectionKind) {
            for (const auto& entry : section.entries) {
                writer(entry);
            }
        }
    }
}

void WriteEvents(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "        (EventLocations." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteLocations(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Locations, [&](const rls::ast::Entry& entry){
        source << "        (Locations." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteExits(
	const SohApTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Exits, [&](const rls::ast::Entry& entry){
        source << "        (Regions." << entry.name << ", lambda bundle: " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void SohApTranspiler::GenerateRegionsSource(rls::OutputWriter& out) const {    
        auto& source = out.open("regions.gen.py");
        source << "# Generated by RLS soh_ap transpiler\n"
            << "\n"
            << "from ...LogicHelpers import *\n"
            << "\n"
            << "if TYPE_CHECKING:\n"
            << "    from ... import SohWorld\n\n"
            << "def set_region_rules(world: \"SohWorld\") -> None:\n";

        // TODO figure out local events and event locations

    for (const auto& [regionName, region] : project.RegionDecls) {
        const auto [extendRegionBegin, extendRegionEnd] = project.ExtendRegionDecls.equal_range(region->key);

        std::string creationString = "Regions." + region->key + ", world, [\n";

        source << "    # " << region->body.name << "\n"
               << "    # Events\n";

        source << "    add_events(" << creationString;
        WriteEvents(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteEvents(*this, source, it->second->sections);
        }
        source << "    ])\n    # Locations\n"
               << "    add_locations(" << creationString;
        WriteLocations(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteLocations(*this, source, it->second->sections);
        }
        source << "    ])\n    # Exits\n"
               << "    connect_regions(" << creationString;
        WriteExits(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteExits(*this, source, it->second->sections);
        }
        source << "    ])\n\n";

        // source << "areaTable[" << region->key << "] = Region("
        //        << "\"" << region->body.name << "\", "
        //        << region->body.scene.value() << ", ";
        
        // source << "{\n    // Events\n";
        // WriteEvents(source, region->body.sections);
        // for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
        //     WriteEvents(source, it->second->sections);
        // }
        // source << "}, {\n    // Locations\n";
        // WriteLocations(source, region->body.sections);
        // for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
        //     WriteLocations(source, it->second->sections);
        // }
        // source << "}, {\n    // Exits\n";
        // WriteExits(source, region->body.sections);
        // for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
        //     WriteExits(source, it->second->sections);
        // }
        // source << "});\n\n";
    }

    // source << "}\n";
}

} // namespace rls::transpilers::soh_ap