#include "soh_ap.h"
#include "section_walk.h"

#include <set>
#include <sstream>
#include <vector>

namespace rls::transpilers::soh_ap {

using ap::WriteEntries;
using ap::InsertToSet;

void SohApTranspiler::writeEnums(rls::OutputWriter& out) const {
	auto& source = out.open("enums.gen.py");

	source
		<< "# Generated by RLS soh_ap transpiler\n"
		<< "from enum import StrEnum, IntEnum, auto, Enum\n";

	std::ostringstream eventLocations;
	std::ostringstream events;
	std::ostringstream regions;
	std::ostringstream locations;

	// Sets to track which enum values have already been emitted, to avoid duplicates across regions and extended regions
	std::set<std::string> emittedEvents;
	std::set<std::string> emittedLocations;

	eventLocations << "class EventLocations(StrEnum):\n"
		<< "    @staticmethod\n"
		<< "    def _generate_next_value_(name, start, count, last_values):\n"
		<< "        new_name = name.replace(\"RR_\", \"\").replace(\"_\", \" \").title()\n"
		<< "        return new_name\n";
	events << "class Events(StrEnum):\n"
		<< "    @staticmethod\n"
		<< "    def _generate_next_value_(name, start, count, last_values):\n"
		<< "        new_name = name.replace(\"LOGIC_\", \"\").replace(\"_\", \" \").title()\n"
		<< "        return new_name\n";
	regions << "class Regions(StrEnum):\n";
	locations << "class Locations(StrEnum):\n"
		<< "    @staticmethod\n"
		<< "    def _generate_next_value_(name, start, count, last_values):\n"
		<< "        new_name = name.replace(\"RC_\", \"\").replace(\"_\", \" \").title()\n"
		<< "        return new_name\n";

	auto writeEventLocations = [&](const std::string& regionKey, const std::vector<rls::ast::Section>& sections) {
		WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry) {
			eventLocations << "    " << regionKey << "_" << entry.name.text << " = auto()\n";
		});
	};

	for (const auto& [regionName, region] : project.RegionDecls) {
		// Do Regions while here
		regions << "    " << region->key.text << " = \"" << region->body.name << "\"\n";

		std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
		const auto extendRegionIt = project.ExtendRegionDecls.find(region->key.text);

		if (extendRegionIt != project.ExtendRegionDecls.end()) {
			extendRegionDecls = extendRegionIt->second;
		}

		// Event Locations
		writeEventLocations(region->key.text, region->body.sections);
		for (const auto* extendRegion : extendRegionDecls) {
			writeEventLocations(region->key.text, extendRegion->sections);
		}

		// Events
		InsertToSet(region->body.sections, rls::ast::SectionKind::Events, emittedEvents);
		for (const auto* extendRegion : extendRegionDecls) {
			InsertToSet(extendRegion->sections, rls::ast::SectionKind::Events, emittedEvents);
		}

		// Locations
		InsertToSet(region->body.sections, rls::ast::SectionKind::Locations, emittedLocations);
		for (const auto* extendRegion : extendRegionDecls) {
			InsertToSet(extendRegion->sections, rls::ast::SectionKind::Locations, emittedLocations);
		}
	}

	// Add distinct events and locations from all regions to the main Events and Locations enums
	for (const auto& event : emittedEvents) {
		events << "    " << event << " = auto()\n";
	}
	for (const auto& location : emittedLocations) {
		locations << "    " << location << " = auto()\n";
	}

	// Output to source
	source << "\n" << eventLocations.str();
	source << "\n" << events.str();
	source << "\n" << regions.str();
	source << "\n" << locations.str();
}

} // namespace rls::transpilers::soh_ap
