#include "soh_ap.h"

namespace rls::transpilers::soh_ap {

std::string SohApTranspiler::regionsPreamble() const {
	return
		"# Generated by RLS soh_ap transpiler\n"
		"from .functions.gen import *\n"
		"\n"
		"if TYPE_CHECKING:\n"
		"    from ... import SohWorld\n"
		"\n"
		"def set_region_rules(world: \"SohWorld\") -> None:\n";
}

std::string SohApTranspiler::regionCreationArgs(const std::string& regionKey) const {
	return "Regions." + regionKey + ", world, [\n";
}

std::string SohApTranspiler::addEventsFn() const {
	return "add_events";
}

std::string SohApTranspiler::addLocationsFn() const {
	return "add_locations";
}

std::string SohApTranspiler::connectRegionsFn() const {
	return "connect_regions";
}

std::string SohApTranspiler::eventEntryLine(
	const std::string& regionKey, const std::string& entryName, const std::string& rule) const {
	return "        (EventLocations." + regionKey + "_" + entryName +
		   ", Events." + entryName + ", lambda " + ruleContextParam() + ": " + rule + "),\n";
}

std::string SohApTranspiler::locationEntryLine(const std::string& entryName, const std::string& rule) const {
	return "        (Locations." + entryName + ", lambda " + ruleContextParam() + ": " + rule + "),\n";
}

std::string SohApTranspiler::exitEntryLine(const std::string& entryName, const std::string& rule) const {
	return "        (Regions." + entryName + ", lambda " + ruleContextParam() + ": " + rule + "),\n";
}

} // namespace rls::transpilers::soh_ap
