#include "soh_ap.h"
#include "section_walk.h"

#include <ostream>
#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace rls::transpilers::soh_ap {

using ap::WriteEntries;
using ap::InsertToSet;
using ap::RegionDisplayName;

namespace {

// Emit a StrEnum whose members are `auto()`-valued. The shared _generate_next_value_ turns
// a member name into its display string by dropping `stripPrefix` and title-casing the rest
// (RC_SONG_FROM_SARIA -> "Song From Saria"), so the values never have to be spelled out.
void writeAutoStrEnum(std::ostream& out, std::string_view className,
	std::string_view stripPrefix, const std::vector<std::string>& members)
{
	out << "\nclass " << className << "(StrEnum):\n"
		<< "    @staticmethod\n"
		<< "    def _generate_next_value_(name, start, count, last_values):\n"
		<< "        return name.replace(\"" << stripPrefix << "\", \"\").replace(\"_\", \" \").title()\n";
	for (const auto& member : members) {
		out << "    " << member << " = auto()\n";
	}
}

// Emit the Python class for one RLS `enum Foo { A, B = 3 }`. Members carry the values sema
// assigned them; a member that somehow lacks one falls back to auto(), since a Python enum
// member must be given a value.
void writeDeclaredEnum(std::ostream& out, std::string_view className, const rls::ast::EnumInfo& info) {
	out << "\nclass " << className << "(IntEnum):\n";
	bool wroteMember = false;
	for (const auto& entry : info.entries) {
		const auto* member = std::get_if<rls::ast::EnumMemberInfo>(&entry);
		if (member == nullptr) {
			// A pattern entry (`RG_*`) names no member -- only extern enums have these, and
			// those are skipped wholesale by the caller.
			continue;
		}
		out << "    " << member->name.text << " = ";
		if (member->value.has_value()) {
			out << *member->value;
		} else {
			out << "auto()";
		}
		out << "\n";
		wroteMember = true;
	}
	if (!wroteMember) {
		out << "    pass\n";
	}
}

} // namespace

void SohApTranspiler::writeEnums(rls::OutputWriter& out) const {
	auto& source = out.open("enums_gen.py");

	source
		<< "# Generated by RLS soh_ap transpiler\n"
		<< "from enum import StrEnum, IntEnum, auto\n";

	// == Enums materialized from the region declarations ======================
	// Region, Check and Logic are extern enums: RLS knows them only as glob patterns, but
	// this project *declares* the values that matter (every region, location and event), so
	// their classes are built from the region walk rather than from the enum declaration.
	std::vector<std::string> eventLocations;   // region x event pairs, in region order
	std::vector<std::string> regions;          // `RR_X = "Display Name"` lines
	std::set<std::string> events;              // deduplicated across regions and extensions
	std::set<std::string> locations;

	for (const auto& [regionName, region] : project.RegionDecls) {
		regions.push_back(region->key.text + " = \"" + RegionDisplayName(*region) + "\"");

		// A region's own sections plus every `extend region` block that targets it.
		std::vector<const rls::ast::ExtendRegionDecl*> extendRegionDecls;
		if (const auto it = project.ExtendRegionDecls.find(region->key.text);
			it != project.ExtendRegionDecls.end()) {
			extendRegionDecls = it->second;
		}

		auto collectFrom = [&](const std::vector<rls::ast::Section>& sections) {
			WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry) {
				eventLocations.push_back(region->key.text + "_" + entry.name.text);
			});
			InsertToSet(sections, rls::ast::SectionKind::Events, events);
			InsertToSet(sections, rls::ast::SectionKind::Locations, locations);
		};

		collectFrom(region->body.sections);
		for (const auto* extendRegion : extendRegionDecls) {
			collectFrom(extendRegion->sections);
		}
	}

	writeAutoStrEnum(source, "EventLocations", "RR_", eventLocations);
	writeAutoStrEnum(source, "Events", "LOGIC_", {events.begin(), events.end()});

	// Unlike the auto() StrEnums above, this class has no _generate_next_value_ to fall back
	// on, so an empty body needs an explicit `pass` to stay valid Python.
	source << "\nclass Regions(StrEnum):\n";
	for (const auto& region : regions) {
		source << "    " << region << "\n";
	}
	if (regions.empty()) {
		source << "    pass\n";
	}

	writeAutoStrEnum(source, "Locations", "RC_", {locations.begin(), locations.end()});

	// == Enums declared directly in RLS =======================================
	// `enum Foo { ... }` carries its members in the AST, so the class is generated here and
	// referenced by its own name (see enumClassName). `extern enum Foo { RG_* }` is a glob
	// pattern over host names -- RLS never learns its members -- so the hand-written world
	// supplies those classes and they are skipped.
	for (const auto& [enumName, info] : project.EnumInfos) {
		if (info.kind != rls::ast::EnumKind::Normal) {
			continue;
		}
		writeDeclaredEnum(source, enumName, info);
	}
}

} // namespace rls::transpilers::soh_ap
