#include "soh_ap.h"

namespace rls::transpilers::soh_ap {

std::string SohApTranspiler::functionsPreamble(const std::set<std::string>& usedNames) const {
	return
		"# Generated by RLS soh_ap transpiler\n" +
		renderImports(usedNames) +
		"\n"
		"if TYPE_CHECKING:\n"
		"    from . import SohWorld\n";
}

std::string SohApTranspiler::pythonTypeName(
	rls::ast::Type type, std::optional<std::string_view> enumName) const {
	using AT = rls::ast::Type;
	switch (type) {
		case AT::Bool: return "bool";
		case AT::Int: return "int";
		// A Condition/Callable lowers to a thunk invoked as `cond(bundle)`: it takes the
		// rule bundle and returns a Rule (see GenerateCallArgument / InvokeExpr).
		case AT::Condition:
		case AT::Callable: return "Callable[[tuple[Regions, \"SohWorld\"]], Rule]";
		// A region/event/location parameter is annotated with the world class its values live
		// in -- the same class renderEnumValue prefixes them with.
		case AT::Region:   return enumClassName("Region").value_or("unsupported_type");
		case AT::Event:    return enumClassName("Event").value_or("unsupported_type");
		case AT::Location: return enumClassName("Location").value_or("unsupported_type");
		default: break;
	}
	// An enum-valued parameter is annotated with the same class renderEnumValue prefixes
	// its values with, so signatures and values agree.
	if (type == AT::Enum && enumName.has_value()) {
		if (auto cls = enumClassName(*enumName)) {
			return *cls;
		}
	}
	return "unsupported_type";
}

} // namespace rls::transpilers::soh_ap
