#include "soh_ap.h"

namespace rls::transpilers::soh_ap {

std::string SohApTranspiler::functionsPreamble() const {
	return
		"# Generated by RLS soh_ap transpiler\n"
		"from .enums.gen import *\n"
		"from .rls_match import rls_match\n";
}

std::string SohApTranspiler::pythonTypeName(rls::ast::Type type) const {
	using AT = rls::ast::Type;
	switch (type) {
		case AT::Bool: return "bool";
		case AT::Int: return "int";
		case AT::Item: return "RandomizerGet";
		case AT::Enemy: return "RandomizerEnemy";
		case AT::Distance: return "EnemyDistance";
		case AT::Trick: return "RandomizerTrick";
		case AT::Setting: return "RandomizerSettingKey";
		case AT::Region: return "RandomizerRegion";
		case AT::Check: return "RandomizerCheck";
		case AT::Logic: return "LogicVal";
		case AT::Scene: return "SceneID";
		case AT::Dungeon: return "DungeonKey";
		case AT::Area: return "RandomizerArea";
		case AT::Trial: return "TrialKey";
		case AT::WaterLevel: return "RandoWaterLeve";
		default: return "unsupported_type";
	}
}

} // namespace rls::transpilers::soh_ap
