#include <gtest/gtest.h>

#include <sstream>
#include <string>
#include <unordered_map>

#include "soh_solver.h"

namespace {

/// In-memory OutputWriter for tests. Captures all output by filename.
class MemoryWriter : public rls::OutputWriter {
public:
	std::ostream& open(const std::string& filename) override {
		return buffers[filename];
	}

	std::string content(const std::string& filename) const {
		auto it = buffers.find(filename);
		return it != buffers.end() ? it->second.str() : "";
	}

	std::unordered_map<std::string, std::ostringstream> buffers;
};

} // namespace

TEST(SohSolverTests, GeneratesHeaderComment) {
	const rls::ast::Project project{};
	MemoryWriter out;

	rls::transpilers::soh_solver::Transpile(project, out);

	EXPECT_EQ(out.content("soh_solver.cpp"),
		"// Generated by RLS soh_solver transpiler\n");
}