#include <gtest/gtest.h>

#include "soh_solver.h"

TEST(SohSolverTests, GeneratesHeaderComment) {
	const rls::ast::File file{};

	EXPECT_EQ(rls::transpilers::soh_solver::Transpile(file),
		"// Generated by RLS soh_solver transpiler");
}