#include "soh.h"

#include <functional>

namespace rls::transpilers::soh {

void SohTranspiler::GenerateRegionsHeader(rls::OutputWriter& out) const {
    auto& header = out.open("regions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
		   << "#pragma once\n"
		   << "\n"
		   << "void RegisterRegions();\n";
}

using EntryWriter = std::function<void(const rls::ast::Entry&)>;
void WriteEntries(const std::vector<rls::ast::Section>& sections,
    rls::ast::SectionKind sectionKind, EntryWriter writer) {
    for (const auto& section : sections) {
        if (section.kind == sectionKind) {
            for (const auto& entry : section.entries) {
                writer(entry);
            }
        }
    }
}

void WriteEvents(
	const SohTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Events, [&](const rls::ast::Entry& entry){
        source << "    EVENT_ACCESS(" << entry.name << ", " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteLocations(
	const SohTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Locations, [&](const rls::ast::Entry& entry){
        source << "    LOCATION(" << entry.name << ", " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void WriteExits(
	const SohTranspiler& transpiler,
	std::ostream& source,
	const std::vector<rls::ast::Section>& sections)
{
    WriteEntries(sections, rls::ast::SectionKind::Exits, [&](const rls::ast::Entry& entry){
        source << "    ENTRANCE(" << entry.name << ", " << transpiler.GenerateExpression(entry.condition) << "),\n";
    });
}

void SohTranspiler::GenerateRegionsSource(rls::OutputWriter& out) const {
    auto& source = out.open("regions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
           << "#include \"regions.gen.h\"\n"
		   << "#include \"functions.gen.h\"\n"
		   << "\n"
		   << "void RegisterRegions() {\n"
           << "\n";
    
    for (const auto& [regionName, region] : project.RegionDecls) {
        const auto [extendRegionBegin, extendRegionEnd] = project.ExtendRegionDecls.equal_range(region->key);

        source << "areaTable[" << region->key << "] = Region("
               << "\"" << region->body.name << "\", "
               << region->body.scene.value() << ", ";
        
        source << "{\n    // Events\n";
        WriteEvents(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteEvents(*this, source, it->second->sections);
        }
        source << "}, {\n    // Locations\n";
        WriteLocations(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteLocations(*this, source, it->second->sections);
        }
        source << "}, {\n    // Exits\n";
        WriteExits(*this, source, region->body.sections);
        for (auto it = extendRegionBegin; it != extendRegionEnd; it++) {
            WriteExits(*this, source, it->second->sections);
        }
        source << "});\n\n";
    }

    source << "}\n";
}

} // namespace rls::transpilers::soh