#include "soh.h"
#include "enum_mappings.h"

#include <sstream>

using AT = rls::ast::Type;

namespace rls::transpilers::soh {

namespace {

void writeEnumDeclarations(std::ostream& out, const rls::ast::Project& project) {
    for (const auto& [enumName, info] : project.EnumInfos) {
        if (info.kind != rls::ast::EnumKind::Normal) {
            continue;
        }

        out << "enum class " << enumName << " : int {\n";
        for (size_t i = 0; i < info.entries.size(); ++i) {
            const auto& entry = info.entries[i];
            if (!std::holds_alternative<rls::ast::EnumMemberInfo>(entry)) {
                continue;
            }

            const auto& member = std::get<rls::ast::EnumMemberInfo>(entry);
            if (i > 0) {
                out << ",\n";
            }
            out << "    " << member.name.text;
            if (member.value.has_value()) {
                out << " = " << *member.value;
            }
        }
        out << "\n};\n";
    }
}

bool hasNormalEnums(const rls::ast::Project& project) {
    for (const auto& [_, info] : project.EnumInfos) {
        if (info.kind == rls::ast::EnumKind::Normal) {
            return true;
        }
    }
    return false;
}

template <typename T>
std::string enumNodeType(const rls::ast::Project& p, const T* node) {
    auto enumType = p.getEnumType(node);
    if (!enumType.has_value()) {
        return "int";
    }

    if (const auto* mapping = findHostEnumMapping(*enumType)) {
        return std::string(mapping->cppType);
    }

    // User/extern enums currently map directly to their enum name.
    return std::string(*enumType);
}

} // namespace

template <typename T>
std::string nodeType(const rls::ast::Project& p, const T* node) {
    const auto type = p.getType(node);
    if (!type.has_value()) {
        return "missing_type";
    }

    switch (type.value()) {
        case AT::Bool: return "bool";
        case AT::Int: return "int";
        case AT::Callable: return "std::function<bool()>";
        case AT::Condition: return "std::function<bool()>";
        case AT::Enum: return enumNodeType(p, node);
		case AT::Region: return "RandomizerRegion";
		case AT::Event: return "LogicVal";
		case AT::Location: return "RandomizerCheck";
        default: return "unsupported_type";
    }
}

std::string functionSignature(
	const SohTranspiler& transpiler,
	const rls::ast::Project& p,
	const rls::ast::DefineDecl* decl,
    const bool includeDefaults)
{
    std::ostringstream sig;
    sig << nodeType(p, decl->body.get()) << " " << decl->name.text << "(";
    for (int i = 0; i < decl->params.size(); i++) {
        const auto& param = decl->params[i];
        sig << "const " << nodeType(p, &param) << " " << param.name.text;
        if (includeDefaults && param.defaultValue != nullptr) {
			sig << " = " + transpiler.GenerateExpression(param.defaultValue);
        }
        if (i < decl->params.size() - 1) {
            sig << ", ";
        }
    }
    sig << ")";
    return sig.str();
}

void SohTranspiler::GenerateFunctionDefinitionsHeader(rls::OutputWriter& out) const {
    auto& header = out.open("functions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
           << "#pragma once\n"
           << "\n"
           << "#include <functional>\n"
           << "#include \"soh/Enhancements/randomizer/location_access.h\"\n"
           << "#include \"soh/Enhancements/randomizer/entrance.h\"\n"
           << "#include \"rls_match.h\"\n"
           << "#include \"rls_host.h\"\n"
           << "\n";

    writeEnumDeclarations(header, project);
    if (hasNormalEnums(project)) {
        header << "\n";
    }

    for (const auto& [name, decl] : project.DefineDecls) {
        header << functionSignature(*this, project, decl, true) << ";\n";
    }
}

void SohTranspiler::GenerateFunctionDefinitionsSource(rls::OutputWriter& out) const {
    auto& source = out.open("functions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
           << "#include \"functions.gen.h\"\n"
           << "#include \"rls_match.h\"\n";


    for (const auto& [name, decl] : project.DefineDecls) {
        source << "\n";
        
        source << functionSignature(*this, project, decl, false) << " {\n";
		source << "    return " << GenerateExpression(decl->body) << ";\n";
        source << "}\n";
    }
}

}