#include "soh.h"
#include "generate_expression.h"

#include <sstream>

using AT = rls::ast::Type;

namespace rls::transpilers::soh {

template <typename T>
std::string nodeType(const rls::ast::Project& p, const T* node) {
    const auto type = p.getType(node);
    if (!type.has_value()) {
        return "missing_type";
    }

    switch (type.value()) {
        case AT::Bool: return "bool";
        case AT::Int: return "int";
        case AT::Item: return "RandomizerGet";
        case AT::Enemy: return "RandomizerEnemy";
        case AT::Distance: return "EnemyDistance";
        case AT::Trick: return "RandomizerTrick";
        case AT::Setting: return "RandomizerSettingKey";
        case AT::Region: return "RandomizerRegion";
        case AT::Check: return "RandomizerCheck";
        case AT::Logic: return "LogicVal";
        case AT::Scene: return "SceneID";
        case AT::Dungeon: return "DungeonKey";
        case AT::Area: return "RandomizerArea";
        case AT::Trial: return "TrialKey";
        case AT::WaterLevel: return "RandoWaterLeve";
        default: return "unsupported_type";
    }
}

std::string functionSignature(const rls::ast::Project& p, const rls::ast::DefineDecl* decl) {
    std::ostringstream sig;
    sig << nodeType(p, decl->body.get()) << " " << decl->name << "(";
    for (int i = 0; i < decl->params.size(); i++) {
        const auto& param = decl->params[i];
        sig << "const " << nodeType(p, &param) << " " << param.name;
        if (param.defaultValue != nullptr) {
            sig << " = " + GenerateExpression(param.defaultValue);
        }
        if (i < decl->params.size() - 1) {
            sig << ", ";
        }
    }
    sig << ")";
    return sig.str();
}

void SohTranspiler::GenerateFunctionDefinitionsHeader(rls::OutputWriter& out) const {
    auto& header = out.open("functions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
           << "#pragma once\n"
           << "\n"
           << "#include \"soh/Enhancements/randomizer/location_access.h\"\n"
           << "#include \"soh/Enhancements/randomizer/entrance.h\"\n"
           << "#include \"rls_match.h\"\n"
           << "\n";

    for (const auto& [name, decl] : project.DefineDecls) {
        header << functionSignature(project, decl) << ";\n";
    }
}

void SohTranspiler::GenerateFunctionDefinitionsSource(rls::OutputWriter& out) const {
    auto& source = out.open("functions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
           << "#include \"functions.gen.h\"\n"
           << "#include \"rls_match.h\"\n";


    for (const auto& [name, decl] : project.DefineDecls) {
        source << "\n";
        
        source << functionSignature(project, decl) << " {\n";
        source << "    return " << GenerateExpression(decl->body) << ";\n";
        source << "}\n";
    }
}

}