#include "generate_functions.h"
#include "generate_expression.h"

#include <sstream>

using AT = rls::ast::Type;

namespace rls::transpilers::soh {

template <typename T>
std::string nodeType(const rls::ast::Project& p, const T* node) {
    const auto type = p.getType(node);
    if (!type.has_value()) {
        return "missing_type";
    }

    switch (type.value()) {
        case AT::Int: return "int";
        case AT::Bool: return "bool";
        default: return "unsupported_type";
    }
}

const std::string& translateFunctionName(const rls::ast::CallExpr& callExpr) {
    static const std::unordered_map<std::string, std::string> funcNameMap = {
        {"has", "logic->HasItem"}
    };
    return funcNameMap.at(callExpr.function);
}

std::string functionSignature(const rls::ast::Project& p, const rls::ast::DefineDecl* decl) {
    std::ostringstream sig;
    sig << nodeType(p, decl->body.get()) << " " << decl->name << "(";
    for (int i = 0; i < decl->params.size(); i++) {
        const auto& param = decl->params[i];
        sig << "const " << nodeType(p, &param) << " " << param.name;
        if (param.defaultValue != nullptr) {
            sig << " = " + GenerateExpression(param.defaultValue);
        }
        if (i < decl->params.size() - 1) {
            sig << ", ";
        }
    }
    sig << ")";
    return sig.str();
}

void GenerateFunctionDefinitionsHeader(const rls::ast::Project& p, rls::OutputWriter& out) {
    auto& header = out.open("functions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
           << "#pragma once\n"
           << "\n"
           << "#include ""soh/Enhancements/randomizer/logic.h""\n"
           << "extern std::shared_ptr<Rando::Logic> logic;\n"
           << "\n";

    for (const auto& [name, decl] : p.DefineDecls) {
        header << functionSignature(p, decl) << ";\n";
    }
}

void GenerateFunctionDefinitionsSource(const rls::ast::Project& p, rls::OutputWriter& out) {
    auto& source = out.open("functions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
           << "#include \"functions.gen.h\"\n";


    for (const auto& [name, decl] : p.DefineDecls) {
        source << "\n";
        
        source << functionSignature(p, decl) << " {\n";
        source << "    return " << GenerateExpression(decl->body) << ";\n";
        source << "}\n";
    }
}

}