#include "generate_regions.h"
#include "generate_expression.h"

namespace rls::transpilers::soh {

void GenerateRegionsHeader(const rls::ast::Project& project, rls::OutputWriter& out) {
    auto& header = out.open("regions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
		   << "#pragma once\n"
		   << "\n"
		   << "void RegisterRegions();\n";
}

void GenerateRegionsSource(const rls::ast::Project& project, rls::OutputWriter& out) {
    auto& source = out.open("regions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
		   << "#include \"functions.gen.h\"\n"
           << "#include \"enemies.gen.h\"\n"
		   << "\n"
		   << "void RegisterRegions() {\n"
           << "\n";
    
    for (const auto& [regionName, region] : project.RegionDecls) {
        source << "areaTable[" << region->key << "] = Region("
               << "\"" << region->body.name << "\", "
               << region->body.scene.value() << ", ";
        
        source << "{\n    // Events\n";
        for (auto& section : region->body.sections) {
            if (section.kind == rls::ast::SectionKind::Events) {
                for (const auto& entry : section.entries) {
                    source << "    EVENT_ACCESS(" << entry.name << ", " << GenerateExpression(entry.condition) << "),\n";
                }
            }
        }
        source << "}, {\n    // Locations\n";
        for (auto& section : region->body.sections) {
            if (section.kind == rls::ast::SectionKind::Locations) {
                for (const auto& entry : section.entries) {
                    source << "    LOCATION(" << entry.name << ", " << GenerateExpression(entry.condition) << "),\n";
                }
            }
        }
        source << "}, {\n    // Exits\n";
        for (auto& section : region->body.sections) {
            if (section.kind == rls::ast::SectionKind::Exits) {
                for (const auto& entry : section.entries) {
                    source << "    ENTRANCE(" << entry.name << ", " << GenerateExpression(entry.condition) << "),\n";
                }
            }
        }
        source << "});\n";
    }

    source << "\n}\n";
}

} // namespace rls::transpilers::soh