#include "soh.h"

namespace rls::transpilers::soh {

void Transpile(const rls::ast::Project& project, rls::OutputWriter& out) {
	out.open("soh.cpp") << "// Generated by RLS soh transpiler\n";
}

} // namespace rls::transpilers::soh
