# Generated by RLS soh_ap transpiler
from enum import StrEnum, IntEnum, auto

class EventLocations(StrEnum):
    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        return name.replace("RR_", "").replace("_", " ").title()
    RR_KF_OUTSIDE_DEKU_TREE_LOGIC_STICK_ACCESS = auto()
    RR_KF_OUTSIDE_DEKU_TREE_LOGIC_NUT_ACCESS = auto()
    RR_KF_OUTSIDE_DEKU_TREE_LOGIC_FAIRY_ACCESS = auto()
    RR_KF_OUTSIDE_DEKU_TREE_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD = auto()
    RR_KF_STORMS_GROTTO_LOGIC_FAIRY_ACCESS = auto()
    RR_KF_STORMS_GROTTO_LOGIC_BUG_ACCESS = auto()
    RR_KF_STORMS_GROTTO_LOGIC_FISH_ACCESS = auto()
    RR_KOKIRI_FOREST_LOGIC_FAIRY_ACCESS = auto()
    RR_KOKIRI_FOREST_LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD = auto()
    RR_ROOT_LOGIC_KAKARIKO_GATE_OPEN = auto()
    RR_ROOT_LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER = auto()
    RR_ROOT_LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER = auto()
    RR_ROOT_LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER = auto()
    RR_ROOT_LOGIC_TH_COULD_FREE_SLOPE_CARPENTER = auto()
    RR_ROOT_LOGIC_TH_RESCUED_ALL_CARPENTERS = auto()
    RR_ROOT_LOGIC_FREED_EPONA = auto()

class Events(StrEnum):
    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        return name.replace("LOGIC_", "").replace("_", " ").title()
    LOGIC_BUG_ACCESS = auto()
    LOGIC_DEKU_TREE_CLEAR = auto()
    LOGIC_FAIRY_ACCESS = auto()
    LOGIC_FISH_ACCESS = auto()
    LOGIC_FOREST_TEMPLE_CLEAR = auto()
    LOGIC_FREED_EPONA = auto()
    LOGIC_KAKARIKO_GATE_OPEN = auto()
    LOGIC_LINKS_COW = auto()
    LOGIC_NUT_ACCESS = auto()
    LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD = auto()
    LOGIC_STICK_ACCESS = auto()
    LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER = auto()
    LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER = auto()
    LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER = auto()
    LOGIC_TH_COULD_FREE_SLOPE_CARPENTER = auto()
    LOGIC_TH_RESCUED_ALL_CARPENTERS = auto()

class Regions(StrEnum):
    RR_ADULT_SPAWN = "Adult Spawn"
    RR_BOLERO_OF_FIRE_WARP = "Bolero of Fire Warp"
    RR_CHILD_SPAWN = "Child Spawn"
    RR_KF_BOULDER_LOOP = "KF Boulder Loop"
    RR_KF_HOUSE_OF_TWINS = "KF House of Twins"
    RR_KF_KNOW_IT_ALL_HOUSE = "KF Know It All House"
    RR_KF_KOKIRI_SHOP = "KF Kokiri Shop"
    RR_KF_LINKS_HOUSE = "KF Link's House"
    RR_KF_LINKS_PORCH = "KF Link's Porch"
    RR_KF_MIDOS_HOUSE = "KF Mido's House"
    RR_KF_OUTSIDE_DEKU_TREE = "KF Outside Deku Tree"
    RR_KF_OUTSIDE_LOST_WOODS = "KF Outside Lost Woods"
    RR_KF_RUPEE_ALCOVE = "KF Alcove"
    RR_KF_SARIAS_HOUSE = "KF Saria's House"
    RR_KF_STORMS_GROTTO = "KF Storms Grotto"
    RR_KOKIRI_FOREST = "Kokiri Forest"
    RR_MINUET_OF_FOREST_WARP = "Minuet of Forest Warp"
    RR_NOCTURNE_OF_SHADOW_WARP = "Nocturne of Shadow Warp"
    RR_PRELUDE_OF_LIGHT_WARP = "Prelude of Light Warp"
    RR_REQUIEM_OF_SPIRIT_WARP = "Requiem of Spirit Warp"
    RR_ROOT = "Root"
    RR_ROOT_EXITS = "Root Exits"
    RR_SERENADE_OF_WATER_WARP = "Serenade of Water Warp"
    RR_NONE = "None"

REGION_SCENE: dict[Regions, str] = {
    Regions.RR_ADULT_SPAWN: "SCENE_ID_MAX",
    Regions.RR_BOLERO_OF_FIRE_WARP: "SCENE_ID_MAX",
    Regions.RR_CHILD_SPAWN: "SCENE_ID_MAX",
    Regions.RR_KF_BOULDER_LOOP: "SCENE_KOKIRI_FOREST",
    Regions.RR_KF_HOUSE_OF_TWINS: "SCENE_TWINS_HOUSE",
    Regions.RR_KF_KNOW_IT_ALL_HOUSE: "SCENE_KNOW_IT_ALL_BROS_HOUSE",
    Regions.RR_KF_KOKIRI_SHOP: "SCENE_KOKIRI_SHOP",
    Regions.RR_KF_LINKS_HOUSE: "SCENE_LINKS_HOUSE",
    Regions.RR_KF_LINKS_PORCH: "SCENE_KOKIRI_FOREST",
    Regions.RR_KF_MIDOS_HOUSE: "SCENE_MIDOS_HOUSE",
    Regions.RR_KF_OUTSIDE_DEKU_TREE: "SCENE_KOKIRI_FOREST",
    Regions.RR_KF_OUTSIDE_LOST_WOODS: "SCENE_KOKIRI_FOREST",
    Regions.RR_KF_RUPEE_ALCOVE: "SCENE_KOKIRI_FOREST",
    Regions.RR_KF_SARIAS_HOUSE: "SCENE_SARIAS_HOUSE",
    Regions.RR_KF_STORMS_GROTTO: "SCENE_GROTTOS",
    Regions.RR_KOKIRI_FOREST: "SCENE_KOKIRI_FOREST",
    Regions.RR_MINUET_OF_FOREST_WARP: "SCENE_ID_MAX",
    Regions.RR_NOCTURNE_OF_SHADOW_WARP: "SCENE_ID_MAX",
    Regions.RR_PRELUDE_OF_LIGHT_WARP: "SCENE_ID_MAX",
    Regions.RR_REQUIEM_OF_SPIRIT_WARP: "SCENE_ID_MAX",
    Regions.RR_ROOT: "SCENE_ID_MAX",
    Regions.RR_ROOT_EXITS: "SCENE_ID_MAX",
    Regions.RR_SERENADE_OF_WATER_WARP: "SCENE_ID_MAX",
    Regions.RR_NONE: "",
}

REGION_QUEST: dict[Regions, str] = {
    Regions.RR_ADULT_SPAWN: "",
    Regions.RR_BOLERO_OF_FIRE_WARP: "",
    Regions.RR_CHILD_SPAWN: "",
    Regions.RR_KF_BOULDER_LOOP: "",
    Regions.RR_KF_HOUSE_OF_TWINS: "",
    Regions.RR_KF_KNOW_IT_ALL_HOUSE: "",
    Regions.RR_KF_KOKIRI_SHOP: "",
    Regions.RR_KF_LINKS_HOUSE: "",
    Regions.RR_KF_LINKS_PORCH: "",
    Regions.RR_KF_MIDOS_HOUSE: "",
    Regions.RR_KF_OUTSIDE_DEKU_TREE: "",
    Regions.RR_KF_OUTSIDE_LOST_WOODS: "",
    Regions.RR_KF_RUPEE_ALCOVE: "",
    Regions.RR_KF_SARIAS_HOUSE: "",
    Regions.RR_KF_STORMS_GROTTO: "",
    Regions.RR_KOKIRI_FOREST: "",
    Regions.RR_MINUET_OF_FOREST_WARP: "",
    Regions.RR_NOCTURNE_OF_SHADOW_WARP: "",
    Regions.RR_PRELUDE_OF_LIGHT_WARP: "",
    Regions.RR_REQUIEM_OF_SPIRIT_WARP: "",
    Regions.RR_ROOT: "",
    Regions.RR_ROOT_EXITS: "",
    Regions.RR_SERENADE_OF_WATER_WARP: "",
    Regions.RR_NONE: "",
}

class TimePasses(IntEnum):
    Auto = 0
    Yes = 1
    No = 2

class WaterLevel(IntEnum):
    WL_LOW = 0
    WL_MID = 1
    WL_HIGH = 2
    WL_LOW_OR_MID = 3
    WL_HIGH_OR_MID = 4
