// Generated by RLS soh transpiler
#include "regions.gen.h"
#include "functions.gen.h"

using namespace Rando;

void register_deku_tree() {

areaTable[RR_DEKU_TREE_BOSS_ENTRYWAY] = Region("Deku Tree Boss Entryway", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BOSS_ROOM, true),
});

areaTable[RR_DEKU_TREE_BOSS_EXIT] = Region("Deku Tree Boss Exit", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_OUTSIDE_BOSS_ROOM, is_vanilla()),
    ENTRANCE(RR_DEKU_TREE_MQ_OUTSIDE_BOSS_ROOM, is_mq()),
});

areaTable[RR_DEKU_TREE_BOSS_ROOM] = Region("Deku Tree Boss Room", SCENE_DEKU_TREE_BOSS, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_CLEAR, can_kill(RandomizerEnemy::RE_GOHMA, EnemyDistance::ED_CLOSE, true, 1, false, false)),
}, {
    // Locations
    LOCATION(RC_QUEEN_GOHMA, flag(LogicVal::LOGIC_DEKU_TREE_CLEAR)),
    LOCATION(RC_DEKU_TREE_QUEEN_GOHMA_HEART, flag(LogicVal::LOGIC_DEKU_TREE_CLEAR)),
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BOSS_EXIT, true),
    ENTRANCE(RR_KF_OUTSIDE_DEKU_TREE, flag(LogicVal::LOGIC_DEKU_TREE_CLEAR)),
});

areaTable[RR_DEKU_TREE_ENTRYWAY] = Region("Deku Tree Entryway", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY, is_vanilla()),
    ENTRANCE(RR_DEKU_TREE_MQ_1F, is_mq()),
    ENTRANCE(RR_KF_OUTSIDE_DEKU_TREE, true),
});

}

void register_deku_tree_mq() {

areaTable[RR_DEKU_TREE_MQ_1F] = Region("Deku Tree MQ 1F", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_kill(RandomizerEnemy::RE_WITHERED_DEKU_BABA, EnemyDistance::ED_CLOSE, true, 1, false, false)),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_ENTRYWAY, true),
    ENTRANCE(RR_DEKU_TREE_MQ_2F, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOOKSHOT)),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT, flag(LogicVal::LOGIC_DEKU_TREE_1F_BROKE_WEB)),
});

areaTable[RR_DEKU_TREE_MQ_2F] = Region("Deku Tree MQ 2F", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_MQ_2F_BURNED_WEB, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_1F, true),
    ENTRANCE(RR_DEKU_TREE_MQ_3F, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_LONGSHOT)),
    ENTRANCE(RR_DEKU_TREE_MQ_EYE_TARGET_ROOM, flag(LogicVal::LOGIC_DEKU_TREE_MQ_2F_BURNED_WEB)),
});

areaTable[RR_DEKU_TREE_MQ_3F] = Region("Deku Tree MQ 3F", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_DEKU_TREE_1F_BROKE_WEB, true),
    EVENT_ACCESS(LOGIC_DEKU_TREE_MQ_2F_BURNED_WEB, can_use(RandomizerGet::RG_STICKS) || can_use(RandomizerGet::RG_FAIRY_BOW)),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_2F, true),
    ENTRANCE(RR_DEKU_TREE_MQ_SLINGSHOT_ROOM, true),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT, true),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT] = Region("Deku Tree MQ Basement", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_DEKU_TREE_B1_BROKE_WEB, can_use(RandomizerGet::RG_STICKS) && (flag(LogicVal::LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK) || is_adult() || can_use(RandomizerGet::RG_HOVER_BOOTS))),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_1F, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_LONGSHOT)),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_SOUTHEAST_ROOM, any_age([]{return can_hit_eye_targets();})),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_FRONT, any_age([]{return can_hit_eye_targets();}) && flag(LogicVal::LOGIC_DEKU_TREE_MQ_CLEARED_SE_ROOM) && any_age([]{return can_use(RandomizerGet::RG_STICKS);})),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_LEDGE, is_adult() || trick(RandomizerTrick::RT_DEKU_B1_SKIP) || can_ground_jump(false) || flag(LogicVal::LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK) || can_use(RandomizerGet::RG_HOVER_BOOTS)),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_BACK_ROOM] = Region("Deku Tree MQ Basement Back Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_GRAVE_ROOM, true),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_GRAVE_ROOM] = Region("Deku Tree MQ Basement Grave Room", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_LEDGE, can_use(RandomizerGet::RG_CRAWL) && any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);})),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_SOUTHWEST_ROOM, true),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_BACK_ROOM, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);})),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_LEDGE] = Region("Deku Tree MQ Basement Ledge", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK, has(RandomizerGet::RG_POWER_BRACELET)),
    EVENT_ACCESS(LOGIC_DEKU_TREE_B1_BROKE_WEB, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_GRAVE_ROOM, can_use(RandomizerGet::RG_CRAWL)),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT, true),
    ENTRANCE(RR_DEKU_TREE_MQ_OUTSIDE_BOSS_ROOM, flag(LogicVal::LOGIC_DEKU_TREE_B1_BROKE_WEB) && (has(RandomizerGet::RG_BRONZE_SCALE) || can_use(RandomizerGet::RG_IRON_BOOTS))),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_SOUTHEAST_ROOM] = Region("Deku Tree MQ Southeast Room", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_MQ_CLEARED_SE_ROOM, can_kill(RandomizerEnemy::RE_MAD_SCRUB, EnemyDistance::ED_CLOSE, true, 1, false, false)),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_FRONT, has_fire_source()),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT, flag(LogicVal::LOGIC_DEKU_TREE_MQ_CLEARED_SE_ROOM)),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_SOUTHWEST_ROOM] = Region("Deku Tree MQ Basement Southwest Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_GRAVE_ROOM, any_age([]{return can_kill(RandomizerEnemy::RE_MAD_SCRUB, EnemyDistance::ED_CLOSE, true, 1, false, false) && can_kill(RandomizerEnemy::RE_KEESE, EnemyDistance::ED_CLOSE, true, 1, false, false);})),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_BACK, any_age([]{return can_kill(RandomizerEnemy::RE_MAD_SCRUB, EnemyDistance::ED_CLOSE, true, 1, false, false) && can_kill(RandomizerEnemy::RE_KEESE, EnemyDistance::ED_CLOSE, true, 1, false, false);})),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_BACK] = Region("Deku Tree MQ Basement Water Room Back", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_kill(RandomizerEnemy::RE_WITHERED_DEKU_BABA, EnemyDistance::ED_CLOSE, true, 1, false, false)),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_SOUTHWEST_ROOM, flag(LogicVal::LOGIC_DEKU_TREE_MQ_WATER_ROOM_TORCHES) && can_pass(RandomizerEnemy::RE_BIG_SKULLTULA, can_use(RandomizerGet::RG_SONG_OF_TIME) ? EnemyDistance::ED_CLOSE : EnemyDistance::ED_SHORT_JUMPSLASH, true)),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_FRONT, trick(RandomizerTrick::RT_DEKU_MQ_LOG) || is_child() && can_shield() || can_use(RandomizerGet::RG_LONGSHOT) || has(RandomizerGet::RG_BRONZE_SCALE) || can_use(RandomizerGet::RG_IRON_BOOTS) && (is_adult() || can_use(RandomizerGet::RG_HOOKSHOT))),
});

areaTable[RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_FRONT] = Region("Deku Tree MQ Basement Water Room Front", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_MQ_WATER_ROOM_TORCHES, can_use(RandomizerGet::RG_FIRE_ARROWS) || can_use(RandomizerGet::RG_STICKS) && (trick(RandomizerTrick::RT_DEKU_MQ_LOG) || is_child() && can_shield())),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_WATER_ROOM_BACK, trick(RandomizerTrick::RT_DEKU_MQ_LOG) || is_child() && can_shield() || can_use(RandomizerGet::RG_LONGSHOT) || can_use(RandomizerGet::RG_HOOKSHOT) && can_use(RandomizerGet::RG_IRON_BOOTS)),
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_SOUTHEAST_ROOM, true),
});

areaTable[RR_DEKU_TREE_MQ_COMPASS_ROOM] = Region("Deku Tree MQ Compass Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_EYE_TARGET_ROOM, true),
    ENTRANCE(RR_DEKU_TREE_MQ_PAST_BOULDER_VINES, (has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOOKSHOT) || is_adult() && can_use(RandomizerGet::RG_SONG_OF_TIME)) && any_age([]{return can_use(RandomizerGet::RG_BOMBCHU_5) || can_use(RandomizerGet::RG_BOMB_BAG) && (can_use(RandomizerGet::RG_SONG_OF_TIME) || is_adult() || can_use(RandomizerGet::RG_HOVER_BOOTS)) || can_use(RandomizerGet::RG_MEGATON_HAMMER) && (is_adult() && can_use(RandomizerGet::RG_SONG_OF_TIME) || trick(RandomizerTrick::RT_DEKU_MQ_COMPASS_GS) && has(RandomizerGet::RG_CLIMB));})),
});

areaTable[RR_DEKU_TREE_MQ_EYE_TARGET_ROOM] = Region("Deku Tree MQ Eye Target Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_COMPASS_ROOM, any_age([]{return can_hit_eye_targets();})),
    ENTRANCE(RR_DEKU_TREE_MQ_2F, true),
});

areaTable[RR_DEKU_TREE_MQ_OUTSIDE_BOSS_ROOM] = Region("Deku Tree MQ Outside Boss Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_BASEMENT_LEDGE, has(RandomizerGet::RG_CLIMB) && (has(RandomizerGet::RG_BRONZE_SCALE) || can_use(RandomizerGet::RG_HOOKSHOT))),
    ENTRANCE(RR_DEKU_TREE_BOSS_ENTRYWAY, any_age([]{return can_reflect_nuts();})),
});

areaTable[RR_DEKU_TREE_MQ_PAST_BOULDER_VINES] = Region("Deku Tree MQ Past Boulder Vines", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_COMPASS_ROOM, blast_or_smash()),
});

areaTable[RR_DEKU_TREE_MQ_SLINGSHOT_ROOM] = Region("Deku Tree MQ Slingshot Room", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_MQ_3F, can_kill(RandomizerEnemy::RE_DEKU_BABA, EnemyDistance::ED_CLOSE, true, 1, false, false)),
});

}

void register_deku_tree_vanilla() {

areaTable[RR_DEKU_TREE_2F_MIDDLE_ROOM] = Region("Deku Tree 2F Middle Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY, any_age([]{return can_reflect_nuts() || can_use(RandomizerGet::RG_MEGATON_HAMMER);})),
    ENTRANCE(RR_DEKU_TREE_SLINGSHOT_ROOM, any_age([]{return can_reflect_nuts() || can_use(RandomizerGet::RG_MEGATON_HAMMER);})),
});

areaTable[RR_DEKU_TREE_BASEMENT_BACK_LOBBY] = Region("Deku Tree Basement Back Lobby", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_TORCH_ROOM, true),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_BACK_ROOM, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);}) && any_age([]{return blast_or_smash();})),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_UPPER, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);}) && can_use(RandomizerGet::RG_CRAWL)),
});

areaTable[RR_DEKU_TREE_BASEMENT_BACK_ROOM] = Region("Deku Tree Basement Back Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_BACK_LOBBY, true),
});

areaTable[RR_DEKU_TREE_BASEMENT_LOWER] = Region("Deku Tree Basement Lower", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_DEKU_TREE_B1_BROKE_WEB, can_use(RandomizerGet::RG_STICKS) && (flag(LogicVal::LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK) || is_adult() || can_use(RandomizerGet::RG_HOVER_BOOTS)) || trick(RandomizerTrick::RT_DEKU_B1_BOW_WEBS) && is_adult() && can_use(RandomizerGet::RG_FAIRY_BOW)),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY, has(RandomizerGet::RG_CLIMB) || is_adult() && can_use(RandomizerGet::RG_LONGSHOT)),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_SCRUB_ROOM, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);})),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_UPPER, is_adult() || trick(RandomizerTrick::RT_DEKU_B1_SKIP) || can_ground_jump(false) || flag(LogicVal::LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK)),
    ENTRANCE(RR_DEKU_TREE_OUTSIDE_BOSS_ROOM, false),
});

areaTable[RR_DEKU_TREE_BASEMENT_SCRUB_ROOM] = Region("Deku Tree Basement Scrub Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_LOWER, true),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_WATER_ROOM_FRONT, any_age([]{return can_hit_eye_targets();})),
});

areaTable[RR_DEKU_TREE_BASEMENT_TORCH_ROOM] = Region("Deku Tree Basement Torch Room", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_WATER_ROOM_BACK, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);})),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_BACK_LOBBY, any_age([]{return has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW);})),
});

areaTable[RR_DEKU_TREE_BASEMENT_UPPER] = Region("Deku Tree Basement Upper", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_DEKU_TREE_PUSHED_BASEMENT_BLOCK, has(RandomizerGet::RG_POWER_BRACELET)),
    EVENT_ACCESS(LOGIC_DEKU_TREE_B1_BROKE_WEB, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_LOWER, true),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_BACK_LOBBY, can_use(RandomizerGet::RG_CRAWL)),
    ENTRANCE(RR_DEKU_TREE_OUTSIDE_BOSS_ROOM, flag(LogicVal::LOGIC_DEKU_TREE_B1_BROKE_WEB) && (has(RandomizerGet::RG_BRONZE_SCALE) || can_use(RandomizerGet::RG_IRON_BOOTS))),
});

areaTable[RR_DEKU_TREE_BASEMENT_WATER_ROOM_BACK] = Region("Deku Tree Basement Water Room Back", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_WATER_ROOM_FRONT, has(RandomizerGet::RG_BRONZE_SCALE) || trick(RandomizerTrick::RT_DEKU_B1_BACKFLIP_OVER_SPIKED_LOG)),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_TORCH_ROOM, true),
});

areaTable[RR_DEKU_TREE_BASEMENT_WATER_ROOM_FRONT] = Region("Deku Tree Basement Water Room Front", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_SCRUB_ROOM, true),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_WATER_ROOM_BACK, has(RandomizerGet::RG_BRONZE_SCALE) || trick(RandomizerTrick::RT_DEKU_B1_BACKFLIP_OVER_SPIKED_LOG)),
});

areaTable[RR_DEKU_TREE_COMPASS_ROOM] = Region("Deku Tree Compass Room", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY, has_fire_source_with_torch() || can_use(RandomizerGet::RG_FAIRY_BOW)),
    ENTRANCE(RR_DEKU_TREE_BOSS_ENTRYWAY, false),
});

areaTable[RR_DEKU_TREE_LOBBY] = Region("Deku Tree Lobby", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_DEKU_TREE_1F_BROKE_WEB, has_fire_source()),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_ENTRYWAY, true),
    ENTRANCE(RR_DEKU_TREE_LOBBY_2F, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOOKSHOT)),
    ENTRANCE(RR_DEKU_TREE_BASEMENT_LOWER, flag(LogicVal::LOGIC_DEKU_TREE_1F_BROKE_WEB)),
    ENTRANCE(RR_DEKU_TREE_OUTSIDE_BOSS_ROOM, false),
    ENTRANCE(RR_DEKU_TREE_BOSS_ENTRYWAY, false),
});

areaTable[RR_DEKU_TREE_LOBBY_2F] = Region("Deku Tree Lobby 2F", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY, true),
    ENTRANCE(RR_DEKU_TREE_LOBBY_3F, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_LONGSHOT)),
    ENTRANCE(RR_DEKU_TREE_2F_MIDDLE_ROOM, true),
});

areaTable[RR_DEKU_TREE_LOBBY_3F] = Region("Deku Tree Lobby 3F", SCENE_DEKU_TREE, {
    // Events
    EVENT_ACCESS(LOGIC_DEKU_TREE_1F_BROKE_WEB, can_pass(RandomizerEnemy::RE_BIG_SKULLTULA, EnemyDistance::ED_CLOSE, true)),
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_LOBBY_2F, true),
    ENTRANCE(RR_DEKU_TREE_COMPASS_ROOM, true),
});

areaTable[RR_DEKU_TREE_OUTSIDE_BOSS_ROOM] = Region("Deku Tree Outside Boss Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_BASEMENT_UPPER, has(RandomizerGet::RG_CLIMB) && (has(RandomizerGet::RG_BRONZE_SCALE) || can_use(RandomizerGet::RG_HOOKSHOT))),
    ENTRANCE(RR_DEKU_TREE_BOSS_ENTRYWAY, any_age([]{return can_reflect_nuts();})),
});

areaTable[RR_DEKU_TREE_SLINGSHOT_ROOM] = Region("Deku Tree Slingshot Room", SCENE_DEKU_TREE, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_2F_MIDDLE_ROOM, true),
});

}

void register_kokiri_forest() {

areaTable[RR_KF_BOULDER_LOOP] = Region("KF Boulder Loop", SCENE_KOKIRI_FOREST, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_KOKIRI_SWORD_CHEST, is_child() && has(RandomizerGet::RG_OPEN_CHEST)),
    LOCATION(RC_KF_BOULDER_RUPEE_1, is_child()),
    LOCATION(RC_KF_BOULDER_RUPEE_2, is_child()),
    LOCATION(RC_KF_CHILD_GRASS_MAZE_1, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_MAZE_2, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_MAZE_3, is_child() && can_cut_shrubs()),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, can_use(RandomizerGet::RG_CRAWL)),
});

areaTable[RR_KF_HOUSE_OF_TWINS] = Region("KF House of Twins", SCENE_TWINS_HOUSE, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_TWINS_HOUSE_POT_1, has(RandomizerGet::RG_POWER_BRACELET)),
    LOCATION(RC_KF_TWINS_HOUSE_POT_2, has(RandomizerGet::RG_POWER_BRACELET)),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_KNOW_IT_ALL_HOUSE] = Region("KF Know It All House", SCENE_KNOW_IT_ALL_BROS_HOUSE, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_BROTHERS_HOUSE_POT_1, has(RandomizerGet::RG_POWER_BRACELET)),
    LOCATION(RC_KF_BROTHERS_HOUSE_POT_2, has(RandomizerGet::RG_POWER_BRACELET)),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_KOKIRI_SHOP] = Region("KF Kokiri Shop", SCENE_KOKIRI_SHOP, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_SHOP_ITEM_1, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_2, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_3, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_4, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_5, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_6, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_7, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
    LOCATION(RC_KF_SHOP_ITEM_8, has(RandomizerGet::RG_SPEAK_KOKIRI) && check_price(RandomizerCheck::RC_UNKNOWN_CHECK) <= wallet_capacity()),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_LINKS_HOUSE] = Region("KF Link's House", SCENE_LINKS_HOUSE, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_LINKS_HOUSE_COW, is_adult() && can_use(RandomizerGet::RG_EPONAS_SONG) && flag(LogicVal::LOGIC_LINKS_COW)),
    LOCATION(RC_KF_LINKS_HOUSE_POT, has(RandomizerGet::RG_POWER_BRACELET)),
}, {
    // Exits
    ENTRANCE(RR_KF_LINKS_PORCH, true),
});

areaTable[RR_KF_LINKS_PORCH] = Region("KF Link's Porch", SCENE_KOKIRI_FOREST, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_KF_LINKS_HOUSE, true),
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_MIDOS_HOUSE] = Region("KF Mido's House", SCENE_MIDOS_HOUSE, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_MIDOS_TOP_LEFT_CHEST, has(RandomizerGet::RG_OPEN_CHEST)),
    LOCATION(RC_KF_MIDOS_TOP_RIGHT_CHEST, has(RandomizerGet::RG_OPEN_CHEST)),
    LOCATION(RC_KF_MIDOS_BOTTOM_LEFT_CHEST, has(RandomizerGet::RG_OPEN_CHEST)),
    LOCATION(RC_KF_MIDOS_BOTTOM_RIGHT_CHEST, has(RandomizerGet::RG_OPEN_CHEST)),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_OUTSIDE_DEKU_TREE] = Region("KF Outside Deku Tree", SCENE_KOKIRI_FOREST, {
    // Events
    EVENT_ACCESS(LOGIC_STICK_ACCESS, can_get_deku_baba_sticks()),
    EVENT_ACCESS(LOGIC_NUT_ACCESS, can_get_deku_baba_nuts()),
    EVENT_ACCESS(LOGIC_FAIRY_ACCESS, call_gossip_fairy_except_suns()),
    EVENT_ACCESS(LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, is_child() && has(RandomizerGet::RG_SPEAK_KOKIRI) && can_use(RandomizerGet::RG_KOKIRI_SWORD) && can_use(RandomizerGet::RG_DEKU_SHIELD)),
}, {
    // Locations
    LOCATION(RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY, call_gossip_fairy_except_suns()),
    LOCATION(RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE_FAIRY_BIG, can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY, call_gossip_fairy_except_suns()),
    LOCATION(RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE_FAIRY_BIG, can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_DEKU_TREE_LEFT_GOSSIP_STONE, true),
    LOCATION(RC_KF_DEKU_TREE_RIGHT_GOSSIP_STONE, true),
}, {
    // Exits
    ENTRANCE(RR_DEKU_TREE_ENTRYWAY, is_child() || setting(RSK_SHUFFLE_DUNGEON_ENTRANCES) != static_cast<int>(RO_DUNGEON_ENTRANCE_SHUFFLE_OFF) && (setting(RSK_FOREST) == static_cast<int>(RO_CLOSED_FOREST_OFF) || flag(LogicVal::LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD))),
    ENTRANCE(RR_KOKIRI_FOREST, is_adult() && (can_pass(RandomizerEnemy::RE_BIG_SKULLTULA, EnemyDistance::ED_CLOSE, true) || flag(LogicVal::LOGIC_DEKU_TREE_CLEAR)) || setting(RSK_FOREST) == static_cast<int>(RO_CLOSED_FOREST_OFF) || flag(LogicVal::LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD)),
});

areaTable[RR_KF_OUTSIDE_LOST_WOODS] = Region("KF Outside Lost Woods", SCENE_KOKIRI_FOREST, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_GOSSIP_STONE_FAIRY, call_gossip_fairy_except_suns()),
    LOCATION(RC_KF_GOSSIP_STONE_FAIRY_BIG, can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_BEAN_RUPEE_1, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RUPEE_2, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RUPEE_3, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RUPEE_4, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RUPEE_5, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RUPEE_6, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_BEAN_RED_RUPEE, is_adult() && can_use(RandomizerGet::RG_BOOMERANG)),
    LOCATION(RC_KF_GOSSIP_STONE, true),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
    ENTRANCE(RR_THE_LOST_WOODS, true),
    ENTRANCE(RR_KF_RUPEE_ALCOVE, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS))),
    ENTRANCE(RR_KF_STORMS_GROTTO, can_open_storms_grotto()),
});

areaTable[RR_KF_RUPEE_ALCOVE] = Region("KF Alcove", SCENE_KOKIRI_FOREST, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_BEAN_RUPEE_1, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RUPEE_2, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RUPEE_3, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RUPEE_4, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RUPEE_5, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RUPEE_6, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
    LOCATION(RC_KF_BEAN_RED_RUPEE, is_adult() && can_use(RandomizerGet::RG_HOVER_BOOTS)),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_SARIAS_HOUSE] = Region("KF Saria's House", SCENE_SARIAS_HOUSE, {
    // Events
}, {
    // Locations
    LOCATION(RC_KF_SARIAS_TOP_LEFT_HEART, true),
    LOCATION(RC_KF_SARIAS_TOP_RIGHT_HEART, true),
    LOCATION(RC_KF_SARIAS_BOTTOM_LEFT_HEART, true),
    LOCATION(RC_KF_SARIAS_BOTTOM_RIGHT_HEART, true),
}, {
    // Exits
    ENTRANCE(RR_KOKIRI_FOREST, true),
});

areaTable[RR_KF_STORMS_GROTTO] = Region("KF Storms Grotto", SCENE_GROTTOS, {
    // Events
    EVENT_ACCESS(LOGIC_FAIRY_ACCESS, call_gossip_fairy() || can_use(RandomizerGet::RG_STICKS)),
    EVENT_ACCESS(LOGIC_BUG_ACCESS, can_cut_shrubs()),
    EVENT_ACCESS(LOGIC_FISH_ACCESS, true),
}, {
    // Locations
    LOCATION(RC_KF_STORMS_GROTTO_CHEST, has(RandomizerGet::RG_OPEN_CHEST)),
    LOCATION(RC_KF_STORMS_GROTTO_BEEHIVE_LEFT, can_break_lower_beehives()),
    LOCATION(RC_KF_STORMS_GROTTO_BEEHIVE_RIGHT, can_break_lower_beehives()),
    LOCATION(RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY, call_gossip_fairy()),
    LOCATION(RC_KF_STORMS_GROTTO_GOSSIP_STONE_FAIRY_BIG, can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_STORMS_GROTTO_FISH, has_bottle()),
    LOCATION(RC_KF_STORMS_GROTTO_GRASS_1, can_cut_shrubs()),
    LOCATION(RC_KF_STORMS_GROTTO_GRASS_2, can_cut_shrubs()),
    LOCATION(RC_KF_STORMS_GROTTO_GRASS_3, can_cut_shrubs()),
    LOCATION(RC_KF_STORMS_GROTTO_GRASS_4, can_cut_shrubs()),
    LOCATION(RC_KF_STORMS_GROTTO_GOSSIP_STONE, true),
}, {
    // Exits
    ENTRANCE(RR_KF_OUTSIDE_LOST_WOODS, true),
});

areaTable[RR_KOKIRI_FOREST] = Region("Kokiri Forest", SCENE_KOKIRI_FOREST, {
    // Events
    EVENT_ACCESS(LOGIC_FAIRY_ACCESS, call_gossip_fairy_except_suns() || is_child() && can_use(RandomizerGet::RG_MAGIC_BEAN) && has(RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) && can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    EVENT_ACCESS(LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD, is_child() && has(RandomizerGet::RG_SPEAK_KOKIRI) && can_use(RandomizerGet::RG_KOKIRI_SWORD) && can_use(RandomizerGet::RG_DEKU_SHIELD)),
}, {
    // Locations
    LOCATION(RC_KF_BEAN_SPROUT_FAIRY_1, is_child() && can_use(RandomizerGet::RG_MAGIC_BEAN) && has(RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) && can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_BEAN_SPROUT_FAIRY_2, is_child() && can_use(RandomizerGet::RG_MAGIC_BEAN) && has(RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) && can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_BEAN_SPROUT_FAIRY_3, is_child() && can_use(RandomizerGet::RG_MAGIC_BEAN) && has(RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) && can_use(RandomizerGet::RG_SONG_OF_STORMS)),
    LOCATION(RC_KF_BRIDGE_RUPEE, is_child()),
    LOCATION(RC_KF_BEHIND_MIDOS_RUPEE, is_child()),
    LOCATION(RC_KF_SOUTH_GRASS_WEST_RUPEE, is_child()),
    LOCATION(RC_KF_SOUTH_GRASS_EAST_RUPEE, is_child()),
    LOCATION(RC_KF_NORTH_GRASS_WEST_RUPEE, is_child()),
    LOCATION(RC_KF_NORTH_GRASS_EAST_RUPEE, is_child()),
    LOCATION(RC_KF_SARIAS_ROOF_WEST_HEART, is_child()),
    LOCATION(RC_KF_SARIAS_ROOF_EAST_HEART, is_child()),
    LOCATION(RC_KF_SARIAS_ROOF_NORTH_HEART, is_child()),
    LOCATION(RC_KF_BEAN_RUPEE_1, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RUPEE_2, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RUPEE_3, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RUPEE_4, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RUPEE_5, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RUPEE_6, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_BEAN_RED_RUPEE, is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || can_use(RandomizerGet::RG_HOVER_BOOTS) || can_use(RandomizerGet::RG_BOOMERANG))),
    LOCATION(RC_KF_GS_KNOW_IT_ALL_HOUSE, is_child() && can_kill(RandomizerEnemy::RE_GOLD_SKULLTULA, EnemyDistance::ED_CLOSE, true, 1, false, false) && can_get_night_time_gs()),
    LOCATION(RC_KF_GS_BEAN_PATCH, can_spawn_soil_skull(RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) && can_kill(RandomizerEnemy::RE_GOLD_SKULLTULA, EnemyDistance::ED_CLOSE, true, 1, false, false)),
    LOCATION(RC_KF_GS_HOUSE_OF_TWINS, is_adult() && can_get_night_time_gs() && (can_get_drop(RandomizerEnemy::RE_GOLD_SKULLTULA, EnemyDistance::ED_BOOMERANG, false) || trick(RandomizerTrick::RT_KF_ADULT_GS) && can_use(RandomizerGet::RG_HOVER_BOOTS) && can_kill(RandomizerEnemy::RE_GOLD_SKULLTULA, EnemyDistance::ED_SHORT_JUMPSLASH, true, 1, false, false))),
    LOCATION(RC_KF_CHILD_GRASS_1, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_2, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_3, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_4, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_5, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_6, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_7, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_8, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_9, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_10, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_11, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_CHILD_GRASS_12, is_child() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_1, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_2, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_3, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_4, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_5, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_6, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_7, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_8, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_9, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_10, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_11, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_12, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_13, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_14, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_15, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_16, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_17, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_18, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_19, is_adult() && can_cut_shrubs()),
    LOCATION(RC_KF_ADULT_GRASS_20, is_adult() && can_cut_shrubs()),
}, {
    // Exits
    ENTRANCE(RR_KF_BOULDER_LOOP, can_use(RandomizerGet::RG_CRAWL)),
    ENTRANCE(RR_KF_LINKS_PORCH, is_child() ? can_climb_ladder() : has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOVER_BOOTS)),
    ENTRANCE(RR_KF_MIDOS_HOUSE, true),
    ENTRANCE(RR_KF_SARIAS_HOUSE, true),
    ENTRANCE(RR_KF_HOUSE_OF_TWINS, true),
    ENTRANCE(RR_KF_KNOW_IT_ALL_HOUSE, true),
    ENTRANCE(RR_KF_KOKIRI_SHOP, true),
    ENTRANCE(RR_KF_OUTSIDE_DEKU_TREE, flag(LogicVal::LOGIC_SHOWED_MIDO_SWORD_AND_SHIELD) || setting(RSK_FOREST) == static_cast<int>(RO_CLOSED_FOREST_OFF) || is_adult() && (can_pass(RandomizerEnemy::RE_BIG_SKULLTULA, EnemyDistance::ED_CLOSE, true) || flag(LogicVal::LOGIC_FOREST_TEMPLE_CLEAR))),
    ENTRANCE(RR_KF_OUTSIDE_LOST_WOODS, has(RandomizerGet::RG_CLIMB) || can_use(RandomizerGet::RG_HOOKSHOT) || is_adult() && (can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL) || trick(RandomizerTrick::RT_UNINTUITIVE_JUMPS))),
    ENTRANCE(RR_KF_RUPEE_ALCOVE, is_adult() && can_plant_bean(RandomizerRegion::RR_KOKIRI_FOREST, RandomizerGet::RG_KOKIRI_FOREST_BEAN_SOUL)),
    ENTRANCE(RR_LW_BRIDGE_FROM_FOREST, is_adult() || setting(RSK_FOREST) != static_cast<int>(RO_CLOSED_FOREST_ON) || flag(LogicVal::LOGIC_DEKU_TREE_CLEAR)),
});

}

void register_root() {

areaTable[RR_ADULT_SPAWN] = Region("Adult Spawn", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_TEMPLE_OF_TIME, true),
});

areaTable[RR_BOLERO_OF_FIRE_WARP] = Region("Bolero of Fire Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DMC_PAD_ENTRY, true),
});

areaTable[RR_CHILD_SPAWN] = Region("Child Spawn", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_KF_LINKS_HOUSE, true),
});

areaTable[RR_MINUET_OF_FOREST_WARP] = Region("Minuet of Forest Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_SACRED_FOREST_MEADOW, true),
});

areaTable[RR_NOCTURNE_OF_SHADOW_WARP] = Region("Nocturne of Shadow Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_GRAVEYARD_WARP_PAD_REGION, true),
});

areaTable[RR_PRELUDE_OF_LIGHT_WARP] = Region("Prelude of Light Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_TEMPLE_OF_TIME, true),
});

areaTable[RR_REQUIEM_OF_SPIRIT_WARP] = Region("Requiem of Spirit Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_DESERT_COLOSSUS, true),
});

areaTable[RR_ROOT] = Region("Root", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
    EVENT_ACCESS(LOGIC_KAKARIKO_GATE_OPEN, setting(RSK_KAK_GATE) == static_cast<int>(RO_KAK_GATE_OPEN)),
    EVENT_ACCESS(LOGIC_TH_COULD_FREE_1_TORCH_CARPENTER, setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FREE)),
    EVENT_ACCESS(LOGIC_TH_COULD_FREE_DOUBLE_CELL_CARPENTER, setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FREE) || setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FAST)),
    EVENT_ACCESS(LOGIC_TH_COULD_FREE_DEAD_END_CARPENTER, setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FREE) || setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FAST)),
    EVENT_ACCESS(LOGIC_TH_COULD_FREE_SLOPE_CARPENTER, setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FREE) || setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FAST)),
    EVENT_ACCESS(LOGIC_TH_RESCUED_ALL_CARPENTERS, setting(RSK_GERUDO_FORTRESS) == static_cast<int>(RO_GF_CARPENTERS_FREE)),
    EVENT_ACCESS(LOGIC_FREED_EPONA, setting(RSK_SKIP_EPONA_RACE) == static_cast<int>(RO_GENERIC_YES)),
}, {
    // Locations
    LOCATION(RC_LINKS_POCKET, true),
    LOCATION(RC_TRIFORCE_COMPLETED, collected_triforce_pieces() >= required_triforce_pieces()),
    LOCATION(RC_SARIA_SONG_HINT, can_use(RandomizerGet::RG_SARIAS_SONG)),
    LOCATION(RC_SONG_FROM_IMPA, setting(RSK_SKIP_CHILD_ZELDA) == static_cast<int>(RO_GENERIC_YES)),
    LOCATION(RC_HC_MALON_EGG, setting(RSK_SKIP_CHILD_ZELDA) == static_cast<int>(RO_GENERIC_YES)),
    LOCATION(RC_HC_ZELDAS_LETTER, setting(RSK_SKIP_CHILD_ZELDA) == static_cast<int>(RO_GENERIC_YES)),
    LOCATION(RC_TOT_MASTER_SWORD, setting(RSK_SELECTED_STARTING_AGE) == static_cast<int>(RO_AGE_ADULT)),
}, {
    // Exits
    ENTRANCE(RR_ROOT_EXITS, true),
});

areaTable[RR_ROOT_EXITS] = Region("Root Exits", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_CHILD_SPAWN, is_child()),
    ENTRANCE(RR_ADULT_SPAWN, is_adult()),
    ENTRANCE(RR_MINUET_OF_FOREST_WARP, can_use(RandomizerGet::RG_MINUET_OF_FOREST)),
    ENTRANCE(RR_BOLERO_OF_FIRE_WARP, can_use(RandomizerGet::RG_BOLERO_OF_FIRE)),
    ENTRANCE(RR_SERENADE_OF_WATER_WARP, can_use(RandomizerGet::RG_SERENADE_OF_WATER)),
    ENTRANCE(RR_NOCTURNE_OF_SHADOW_WARP, can_use(RandomizerGet::RG_NOCTURNE_OF_SHADOW)),
    ENTRANCE(RR_REQUIEM_OF_SPIRIT_WARP, can_use(RandomizerGet::RG_REQUIEM_OF_SPIRIT)),
    ENTRANCE(RR_PRELUDE_OF_LIGHT_WARP, can_use(RandomizerGet::RG_PRELUDE_OF_LIGHT)),
});

areaTable[RR_SERENADE_OF_WATER_WARP] = Region("Serenade of Water Warp", SCENE_ID_MAX, false, {RA_LINKS_POCKET}, {
    // Events
}, {
    // Locations
}, {
    // Exits
    ENTRANCE(RR_LAKE_HYLIA, true),
});

}

void RegisterRegions() {
    register_deku_tree();
    register_deku_tree_mq();
    register_deku_tree_vanilla();
    register_kokiri_forest();
    register_root();
}
