#include "ap.h"

namespace rls::transpilers::ap {

void Transpile(const rls::ast::Project& project, rls::OutputWriter& out) {
	out.open("ap.py") << "# Generated by RLS ap transpiler\n";
}

} // namespace rls::transpilers::ap
