#include "soh_solver.h"

namespace rls::transpilers::soh_solver {

void Transpile(const rls::ast::Project& project, rls::OutputWriter& out) {
	out.open("soh_solver.cpp") << "// Generated by RLS soh_solver transpiler\n";
}

} // namespace rls::transpilers::soh_solver
