#include "soh_solver.h"

namespace rls::transpilers::soh_solver {

std::string Transpile(const rls::ast::File& file) {
	return "// Generated by RLS soh_solver transpiler";
}

} // namespace rls::transpilers::soh_solver
